// Generated by gencpp from file perception_msgs/DogState.msg
// DO NOT EDIT!


#ifndef PERCEPTION_MSGS_MESSAGE_DOGSTATE_H
#define PERCEPTION_MSGS_MESSAGE_DOGSTATE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose.h>
#include <perception_msgs/AlarmEntry.h>

namespace perception_msgs
{
template <class ContainerAllocator>
struct DogState_
{
  typedef DogState_<ContainerAllocator> Type;

  DogState_()
    : battery(0.0)
    , chargingState(0)
    , gesture(0)
    , speed(0.0)
    , person_state(0)
    , target_position()
    , alarmInfo()  {
    }
  DogState_(const ContainerAllocator& _alloc)
    : battery(0.0)
    , chargingState(0)
    , gesture(0)
    , speed(0.0)
    , person_state(0)
    , target_position(_alloc)
    , alarmInfo(_alloc)  {
  (void)_alloc;
    }



   typedef double _battery_type;
  _battery_type battery;

   typedef uint8_t _chargingState_type;
  _chargingState_type chargingState;

   typedef uint8_t _gesture_type;
  _gesture_type gesture;

   typedef double _speed_type;
  _speed_type speed;

   typedef uint8_t _person_state_type;
  _person_state_type person_state;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _target_position_type;
  _target_position_type target_position;

   typedef std::vector< ::perception_msgs::AlarmEntry_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::perception_msgs::AlarmEntry_<ContainerAllocator> >> _alarmInfo_type;
  _alarmInfo_type alarmInfo;





  typedef boost::shared_ptr< ::perception_msgs::DogState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::perception_msgs::DogState_<ContainerAllocator> const> ConstPtr;

}; // struct DogState_

typedef ::perception_msgs::DogState_<std::allocator<void> > DogState;

typedef boost::shared_ptr< ::perception_msgs::DogState > DogStatePtr;
typedef boost::shared_ptr< ::perception_msgs::DogState const> DogStateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::perception_msgs::DogState_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::perception_msgs::DogState_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::perception_msgs::DogState_<ContainerAllocator1> & lhs, const ::perception_msgs::DogState_<ContainerAllocator2> & rhs)
{
  return lhs.battery == rhs.battery &&
    lhs.chargingState == rhs.chargingState &&
    lhs.gesture == rhs.gesture &&
    lhs.speed == rhs.speed &&
    lhs.person_state == rhs.person_state &&
    lhs.target_position == rhs.target_position &&
    lhs.alarmInfo == rhs.alarmInfo;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::perception_msgs::DogState_<ContainerAllocator1> & lhs, const ::perception_msgs::DogState_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace perception_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::perception_msgs::DogState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::perception_msgs::DogState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::perception_msgs::DogState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::perception_msgs::DogState_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::perception_msgs::DogState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::perception_msgs::DogState_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::perception_msgs::DogState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "37a76525c34080656fe716b1e4427824";
  }

  static const char* value(const ::perception_msgs::DogState_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x37a76525c3408065ULL;
  static const uint64_t static_value2 = 0x6fe716b1e4427824ULL;
};

template<class ContainerAllocator>
struct DataType< ::perception_msgs::DogState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "perception_msgs/DogState";
  }

  static const char* value(const ::perception_msgs::DogState_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::perception_msgs::DogState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# 电量\n"
"float64 battery\n"
"#充电状态   0：空闲 1: 准备充电 2：充电中 \n"
"uint8 chargingState\n"
"#手势\n"
"uint8 gesture\n"
"#速度 \n"
"float64 speed\n"
"#主人识别状态\n"
"uint8 person_state\n"
"# 目标点\n"
"geometry_msgs/Pose target_position\n"
"#报警信息\n"
"AlarmEntry[] alarmInfo\n"
"#动作信息\n"
"#ActionEntry[] actions\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
"\n"
"================================================================================\n"
"MSG: perception_msgs/AlarmEntry\n"
"int32  id\n"
"int32  source\n"
"int32  level\n"
"int32  status\n"
"string message\n"
;
  }

  static const char* value(const ::perception_msgs::DogState_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::perception_msgs::DogState_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.battery);
      stream.next(m.chargingState);
      stream.next(m.gesture);
      stream.next(m.speed);
      stream.next(m.person_state);
      stream.next(m.target_position);
      stream.next(m.alarmInfo);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DogState_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::perception_msgs::DogState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::perception_msgs::DogState_<ContainerAllocator>& v)
  {
    s << indent << "battery: ";
    Printer<double>::stream(s, indent + "  ", v.battery);
    s << indent << "chargingState: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.chargingState);
    s << indent << "gesture: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.gesture);
    s << indent << "speed: ";
    Printer<double>::stream(s, indent + "  ", v.speed);
    s << indent << "person_state: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.person_state);
    s << indent << "target_position: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.target_position);
    s << indent << "alarmInfo[]" << std::endl;
    for (size_t i = 0; i < v.alarmInfo.size(); ++i)
    {
      s << indent << "  alarmInfo[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::perception_msgs::AlarmEntry_<ContainerAllocator> >::stream(s, indent + "    ", v.alarmInfo[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // PERCEPTION_MSGS_MESSAGE_DOGSTATE_H
