# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from quad_msgs/RobotPlanDiagnostics.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class RobotPlanDiagnostics(genpy.Message):
  _md5sum = "4ba495ddc8d93cb86ca454812d102149"
  _type = "quad_msgs/RobotPlanDiagnostics"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """# This is a message to hold local plan diagnostics

float64 compute_time
float64 cost
uint32 iterations
uint32 horizon_length
uint32[] complexity_schedule
float64[] element_times
"""
  __slots__ = ['compute_time','cost','iterations','horizon_length','complexity_schedule','element_times']
  _slot_types = ['float64','float64','uint32','uint32','uint32[]','float64[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       compute_time,cost,iterations,horizon_length,complexity_schedule,element_times

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(RobotPlanDiagnostics, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.compute_time is None:
        self.compute_time = 0.
      if self.cost is None:
        self.cost = 0.
      if self.iterations is None:
        self.iterations = 0
      if self.horizon_length is None:
        self.horizon_length = 0
      if self.complexity_schedule is None:
        self.complexity_schedule = []
      if self.element_times is None:
        self.element_times = []
    else:
      self.compute_time = 0.
      self.cost = 0.
      self.iterations = 0
      self.horizon_length = 0
      self.complexity_schedule = []
      self.element_times = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_2d2I().pack(_x.compute_time, _x.cost, _x.iterations, _x.horizon_length))
      length = len(self.complexity_schedule)
      buff.write(_struct_I.pack(length))
      pattern = '<%sI'%length
      buff.write(struct.Struct(pattern).pack(*self.complexity_schedule))
      length = len(self.element_times)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(struct.Struct(pattern).pack(*self.element_times))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 24
      (_x.compute_time, _x.cost, _x.iterations, _x.horizon_length,) = _get_struct_2d2I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sI'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.complexity_schedule = s.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.element_times = s.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_2d2I().pack(_x.compute_time, _x.cost, _x.iterations, _x.horizon_length))
      length = len(self.complexity_schedule)
      buff.write(_struct_I.pack(length))
      pattern = '<%sI'%length
      buff.write(self.complexity_schedule.tostring())
      length = len(self.element_times)
      buff.write(_struct_I.pack(length))
      pattern = '<%sd'%length
      buff.write(self.element_times.tostring())
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 24
      (_x.compute_time, _x.cost, _x.iterations, _x.horizon_length,) = _get_struct_2d2I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sI'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.complexity_schedule = numpy.frombuffer(str[start:end], dtype=numpy.uint32, count=length)
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      pattern = '<%sd'%length
      start = end
      s = struct.Struct(pattern)
      end += s.size
      self.element_times = numpy.frombuffer(str[start:end], dtype=numpy.float64, count=length)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2d2I = None
def _get_struct_2d2I():
    global _struct_2d2I
    if _struct_2d2I is None:
        _struct_2d2I = struct.Struct("<2d2I")
    return _struct_2d2I
