Headers   header     #  
int32   turn_lamp_ctrl     # 转向灯 TURN_INACTIVE_SIGNAL:0 TURN_LEFT_SIGNAL:1 TURN_RIGHT_SIGNAL:2 TURN_INVALID_SIGNAL:3
int32   high_beam_ctrl     # 0 关闭 1 开启 2 不响应
int32   low_beam_ctrl     # 0 关闭 1 开启 2 不响应
int32   horn_ctrl     # 0 关闭 1 开启 2 不响应
int32   front_wiper_ctrl     # 前雨刮器 0 关闭 1 开启
int32   rear_wiper_ctrl     # 后雨刮器 0 关闭 1 开启
int32   position_lamp_ctrl     # 位置灯 0 关闭 1 开启
int32   front_fog_lamp_ctrl     # 前雾灯 0 关闭 1 开启
int32   rear_fog_lamp_ctrl     # 后雾灯 0 关闭 1 开启
int32   brake_lamp_ctrl     # 刹车灯 一般情况自动控制 0 关闭 1 开启
int32   alarm_lamp_ctrl     # 警报灯 双闪 0 关闭 1 开启
int32   lf_door_ctrl     # 左前门控制 0 关闭 1 开启
int32   rf_door_ctrl     # 右前门控制 0 关闭 1 开启
int32   lr_door_ctrl     # 左后门控制 0 关闭 1 开启
int32   rr_door_ctrl     # 右后门控制 0 关闭 1 开启
