# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from ros_interface/GaussianInfo.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class GaussianInfo(genpy.Message):
  _md5sum = "e7dd0c5b6f01ab6076107f4fff84ee4e"
  _type = "ros_interface/GaussianInfo"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """float64   sigma_x     # 标准差x
float64   sigma_y     # 标准差y
float64   correlation     # 相关性
float64   area_probability     # Information of representative uncertainty area
float64   ellipse_a     # 椭圆长轴
float64   ellipse_b     # 椭圆短轴
float64   theta_a     # 椭圆朝向
"""
  __slots__ = ['sigma_x','sigma_y','correlation','area_probability','ellipse_a','ellipse_b','theta_a']
  _slot_types = ['float64','float64','float64','float64','float64','float64','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       sigma_x,sigma_y,correlation,area_probability,ellipse_a,ellipse_b,theta_a

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(GaussianInfo, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.sigma_x is None:
        self.sigma_x = 0.
      if self.sigma_y is None:
        self.sigma_y = 0.
      if self.correlation is None:
        self.correlation = 0.
      if self.area_probability is None:
        self.area_probability = 0.
      if self.ellipse_a is None:
        self.ellipse_a = 0.
      if self.ellipse_b is None:
        self.ellipse_b = 0.
      if self.theta_a is None:
        self.theta_a = 0.
    else:
      self.sigma_x = 0.
      self.sigma_y = 0.
      self.correlation = 0.
      self.area_probability = 0.
      self.ellipse_a = 0.
      self.ellipse_b = 0.
      self.theta_a = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_7d().pack(_x.sigma_x, _x.sigma_y, _x.correlation, _x.area_probability, _x.ellipse_a, _x.ellipse_b, _x.theta_a))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 56
      (_x.sigma_x, _x.sigma_y, _x.correlation, _x.area_probability, _x.ellipse_a, _x.ellipse_b, _x.theta_a,) = _get_struct_7d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_7d().pack(_x.sigma_x, _x.sigma_y, _x.correlation, _x.area_probability, _x.ellipse_a, _x.ellipse_b, _x.theta_a))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 56
      (_x.sigma_x, _x.sigma_y, _x.correlation, _x.area_probability, _x.ellipse_a, _x.ellipse_b, _x.theta_a,) = _get_struct_7d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_7d = None
def _get_struct_7d():
    global _struct_7d
    if _struct_7d is None:
        _struct_7d = struct.Struct("<7d")
    return _struct_7d
