# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from ros_interface/Ins.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import ros_interface.msg
import std_msgs.msg

class Ins(genpy.Message):
  _md5sum = "a208bce72b0cc6abb54188331564ad26"
  _type = "ros_interface/Ins"
  _has_header = True  # flag to mark the presence of a Header object
  _full_text = """Header   header     # 头部信息
bool   is_valid     # 数据有效性标志位
float64   latitude     # 纬度信息
float64   longitude     # 经度信息
float64   elevation     # 海拔信息
Point3D   utm_position     # UTM坐标位置
int32   utm_zone_mumber     # UTM区号
uint8   utm_zone_char     # UTM区号
Point3D   attitude     # 三轴姿态
Point3D   linear_velocity     # 线速度信息
Point3D   sd_position     # 位置标准差
Point3D   sd_attitude     # 姿态标准差
Point3D   sd_velocity     # 速度标准差
float64   cep68     # cep68数据位
float64   cep95     # cep95数据位
float64   second     # 时间
int32   sat_use_num     # 使用卫星数
int32   sat_in_view_num     # 可见卫星数
uint16   solution_status     # 求解状态
uint16   position_type     # 定位状态
float64   p_dop     # pDop数据位
float64   h_dop     # hDop数据位
float64   v_dop     # vDop数据位
Point3D   attitude_dual     # 双天线姿态
Point3D   sd_angle_dual     # 双天线角度标准差
float64   base_line_length_dual     # 双天线距离
int32   solution_status_dual     # 双天线求解状态
int32   position_type_dual     # 双天线定位状态
int32   solution_source_dual     # 双天线求解源
uint32   aoc     # Aoc数据位
uint32   rtk_baseline     # RTK基线信息
Point3D   angular_velocity     # 角速度信息
Point3D   acceleration     # 加速度信息

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id

================================================================================
MSG: ros_interface/Point3D
float64   x     # 位置坐标x
float64   y     # 位置坐标y
float64   z     # 位置坐标z
"""
  __slots__ = ['header','is_valid','latitude','longitude','elevation','utm_position','utm_zone_mumber','utm_zone_char','attitude','linear_velocity','sd_position','sd_attitude','sd_velocity','cep68','cep95','second','sat_use_num','sat_in_view_num','solution_status','position_type','p_dop','h_dop','v_dop','attitude_dual','sd_angle_dual','base_line_length_dual','solution_status_dual','position_type_dual','solution_source_dual','aoc','rtk_baseline','angular_velocity','acceleration']
  _slot_types = ['std_msgs/Header','bool','float64','float64','float64','ros_interface/Point3D','int32','uint8','ros_interface/Point3D','ros_interface/Point3D','ros_interface/Point3D','ros_interface/Point3D','ros_interface/Point3D','float64','float64','float64','int32','int32','uint16','uint16','float64','float64','float64','ros_interface/Point3D','ros_interface/Point3D','float64','int32','int32','int32','uint32','uint32','ros_interface/Point3D','ros_interface/Point3D']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,is_valid,latitude,longitude,elevation,utm_position,utm_zone_mumber,utm_zone_char,attitude,linear_velocity,sd_position,sd_attitude,sd_velocity,cep68,cep95,second,sat_use_num,sat_in_view_num,solution_status,position_type,p_dop,h_dop,v_dop,attitude_dual,sd_angle_dual,base_line_length_dual,solution_status_dual,position_type_dual,solution_source_dual,aoc,rtk_baseline,angular_velocity,acceleration

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Ins, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.is_valid is None:
        self.is_valid = False
      if self.latitude is None:
        self.latitude = 0.
      if self.longitude is None:
        self.longitude = 0.
      if self.elevation is None:
        self.elevation = 0.
      if self.utm_position is None:
        self.utm_position = ros_interface.msg.Point3D()
      if self.utm_zone_mumber is None:
        self.utm_zone_mumber = 0
      if self.utm_zone_char is None:
        self.utm_zone_char = 0
      if self.attitude is None:
        self.attitude = ros_interface.msg.Point3D()
      if self.linear_velocity is None:
        self.linear_velocity = ros_interface.msg.Point3D()
      if self.sd_position is None:
        self.sd_position = ros_interface.msg.Point3D()
      if self.sd_attitude is None:
        self.sd_attitude = ros_interface.msg.Point3D()
      if self.sd_velocity is None:
        self.sd_velocity = ros_interface.msg.Point3D()
      if self.cep68 is None:
        self.cep68 = 0.
      if self.cep95 is None:
        self.cep95 = 0.
      if self.second is None:
        self.second = 0.
      if self.sat_use_num is None:
        self.sat_use_num = 0
      if self.sat_in_view_num is None:
        self.sat_in_view_num = 0
      if self.solution_status is None:
        self.solution_status = 0
      if self.position_type is None:
        self.position_type = 0
      if self.p_dop is None:
        self.p_dop = 0.
      if self.h_dop is None:
        self.h_dop = 0.
      if self.v_dop is None:
        self.v_dop = 0.
      if self.attitude_dual is None:
        self.attitude_dual = ros_interface.msg.Point3D()
      if self.sd_angle_dual is None:
        self.sd_angle_dual = ros_interface.msg.Point3D()
      if self.base_line_length_dual is None:
        self.base_line_length_dual = 0.
      if self.solution_status_dual is None:
        self.solution_status_dual = 0
      if self.position_type_dual is None:
        self.position_type_dual = 0
      if self.solution_source_dual is None:
        self.solution_source_dual = 0
      if self.aoc is None:
        self.aoc = 0
      if self.rtk_baseline is None:
        self.rtk_baseline = 0
      if self.angular_velocity is None:
        self.angular_velocity = ros_interface.msg.Point3D()
      if self.acceleration is None:
        self.acceleration = ros_interface.msg.Point3D()
    else:
      self.header = std_msgs.msg.Header()
      self.is_valid = False
      self.latitude = 0.
      self.longitude = 0.
      self.elevation = 0.
      self.utm_position = ros_interface.msg.Point3D()
      self.utm_zone_mumber = 0
      self.utm_zone_char = 0
      self.attitude = ros_interface.msg.Point3D()
      self.linear_velocity = ros_interface.msg.Point3D()
      self.sd_position = ros_interface.msg.Point3D()
      self.sd_attitude = ros_interface.msg.Point3D()
      self.sd_velocity = ros_interface.msg.Point3D()
      self.cep68 = 0.
      self.cep95 = 0.
      self.second = 0.
      self.sat_use_num = 0
      self.sat_in_view_num = 0
      self.solution_status = 0
      self.position_type = 0
      self.p_dop = 0.
      self.h_dop = 0.
      self.v_dop = 0.
      self.attitude_dual = ros_interface.msg.Point3D()
      self.sd_angle_dual = ros_interface.msg.Point3D()
      self.base_line_length_dual = 0.
      self.solution_status_dual = 0
      self.position_type_dual = 0
      self.solution_source_dual = 0
      self.aoc = 0
      self.rtk_baseline = 0
      self.angular_velocity = ros_interface.msg.Point3D()
      self.acceleration = ros_interface.msg.Point3D()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_B6diB18d2i2H10d3i2I6d().pack(_x.is_valid, _x.latitude, _x.longitude, _x.elevation, _x.utm_position.x, _x.utm_position.y, _x.utm_position.z, _x.utm_zone_mumber, _x.utm_zone_char, _x.attitude.x, _x.attitude.y, _x.attitude.z, _x.linear_velocity.x, _x.linear_velocity.y, _x.linear_velocity.z, _x.sd_position.x, _x.sd_position.y, _x.sd_position.z, _x.sd_attitude.x, _x.sd_attitude.y, _x.sd_attitude.z, _x.sd_velocity.x, _x.sd_velocity.y, _x.sd_velocity.z, _x.cep68, _x.cep95, _x.second, _x.sat_use_num, _x.sat_in_view_num, _x.solution_status, _x.position_type, _x.p_dop, _x.h_dop, _x.v_dop, _x.attitude_dual.x, _x.attitude_dual.y, _x.attitude_dual.z, _x.sd_angle_dual.x, _x.sd_angle_dual.y, _x.sd_angle_dual.z, _x.base_line_length_dual, _x.solution_status_dual, _x.position_type_dual, _x.solution_source_dual, _x.aoc, _x.rtk_baseline, _x.angular_velocity.x, _x.angular_velocity.y, _x.angular_velocity.z, _x.acceleration.x, _x.acceleration.y, _x.acceleration.z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.utm_position is None:
        self.utm_position = ros_interface.msg.Point3D()
      if self.attitude is None:
        self.attitude = ros_interface.msg.Point3D()
      if self.linear_velocity is None:
        self.linear_velocity = ros_interface.msg.Point3D()
      if self.sd_position is None:
        self.sd_position = ros_interface.msg.Point3D()
      if self.sd_attitude is None:
        self.sd_attitude = ros_interface.msg.Point3D()
      if self.sd_velocity is None:
        self.sd_velocity = ros_interface.msg.Point3D()
      if self.attitude_dual is None:
        self.attitude_dual = ros_interface.msg.Point3D()
      if self.sd_angle_dual is None:
        self.sd_angle_dual = ros_interface.msg.Point3D()
      if self.angular_velocity is None:
        self.angular_velocity = ros_interface.msg.Point3D()
      if self.acceleration is None:
        self.acceleration = ros_interface.msg.Point3D()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 358
      (_x.is_valid, _x.latitude, _x.longitude, _x.elevation, _x.utm_position.x, _x.utm_position.y, _x.utm_position.z, _x.utm_zone_mumber, _x.utm_zone_char, _x.attitude.x, _x.attitude.y, _x.attitude.z, _x.linear_velocity.x, _x.linear_velocity.y, _x.linear_velocity.z, _x.sd_position.x, _x.sd_position.y, _x.sd_position.z, _x.sd_attitude.x, _x.sd_attitude.y, _x.sd_attitude.z, _x.sd_velocity.x, _x.sd_velocity.y, _x.sd_velocity.z, _x.cep68, _x.cep95, _x.second, _x.sat_use_num, _x.sat_in_view_num, _x.solution_status, _x.position_type, _x.p_dop, _x.h_dop, _x.v_dop, _x.attitude_dual.x, _x.attitude_dual.y, _x.attitude_dual.z, _x.sd_angle_dual.x, _x.sd_angle_dual.y, _x.sd_angle_dual.z, _x.base_line_length_dual, _x.solution_status_dual, _x.position_type_dual, _x.solution_source_dual, _x.aoc, _x.rtk_baseline, _x.angular_velocity.x, _x.angular_velocity.y, _x.angular_velocity.z, _x.acceleration.x, _x.acceleration.y, _x.acceleration.z,) = _get_struct_B6diB18d2i2H10d3i2I6d().unpack(str[start:end])
      self.is_valid = bool(self.is_valid)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_B6diB18d2i2H10d3i2I6d().pack(_x.is_valid, _x.latitude, _x.longitude, _x.elevation, _x.utm_position.x, _x.utm_position.y, _x.utm_position.z, _x.utm_zone_mumber, _x.utm_zone_char, _x.attitude.x, _x.attitude.y, _x.attitude.z, _x.linear_velocity.x, _x.linear_velocity.y, _x.linear_velocity.z, _x.sd_position.x, _x.sd_position.y, _x.sd_position.z, _x.sd_attitude.x, _x.sd_attitude.y, _x.sd_attitude.z, _x.sd_velocity.x, _x.sd_velocity.y, _x.sd_velocity.z, _x.cep68, _x.cep95, _x.second, _x.sat_use_num, _x.sat_in_view_num, _x.solution_status, _x.position_type, _x.p_dop, _x.h_dop, _x.v_dop, _x.attitude_dual.x, _x.attitude_dual.y, _x.attitude_dual.z, _x.sd_angle_dual.x, _x.sd_angle_dual.y, _x.sd_angle_dual.z, _x.base_line_length_dual, _x.solution_status_dual, _x.position_type_dual, _x.solution_source_dual, _x.aoc, _x.rtk_baseline, _x.angular_velocity.x, _x.angular_velocity.y, _x.angular_velocity.z, _x.acceleration.x, _x.acceleration.y, _x.acceleration.z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.utm_position is None:
        self.utm_position = ros_interface.msg.Point3D()
      if self.attitude is None:
        self.attitude = ros_interface.msg.Point3D()
      if self.linear_velocity is None:
        self.linear_velocity = ros_interface.msg.Point3D()
      if self.sd_position is None:
        self.sd_position = ros_interface.msg.Point3D()
      if self.sd_attitude is None:
        self.sd_attitude = ros_interface.msg.Point3D()
      if self.sd_velocity is None:
        self.sd_velocity = ros_interface.msg.Point3D()
      if self.attitude_dual is None:
        self.attitude_dual = ros_interface.msg.Point3D()
      if self.sd_angle_dual is None:
        self.sd_angle_dual = ros_interface.msg.Point3D()
      if self.angular_velocity is None:
        self.angular_velocity = ros_interface.msg.Point3D()
      if self.acceleration is None:
        self.acceleration = ros_interface.msg.Point3D()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 358
      (_x.is_valid, _x.latitude, _x.longitude, _x.elevation, _x.utm_position.x, _x.utm_position.y, _x.utm_position.z, _x.utm_zone_mumber, _x.utm_zone_char, _x.attitude.x, _x.attitude.y, _x.attitude.z, _x.linear_velocity.x, _x.linear_velocity.y, _x.linear_velocity.z, _x.sd_position.x, _x.sd_position.y, _x.sd_position.z, _x.sd_attitude.x, _x.sd_attitude.y, _x.sd_attitude.z, _x.sd_velocity.x, _x.sd_velocity.y, _x.sd_velocity.z, _x.cep68, _x.cep95, _x.second, _x.sat_use_num, _x.sat_in_view_num, _x.solution_status, _x.position_type, _x.p_dop, _x.h_dop, _x.v_dop, _x.attitude_dual.x, _x.attitude_dual.y, _x.attitude_dual.z, _x.sd_angle_dual.x, _x.sd_angle_dual.y, _x.sd_angle_dual.z, _x.base_line_length_dual, _x.solution_status_dual, _x.position_type_dual, _x.solution_source_dual, _x.aoc, _x.rtk_baseline, _x.angular_velocity.x, _x.angular_velocity.y, _x.angular_velocity.z, _x.acceleration.x, _x.acceleration.y, _x.acceleration.z,) = _get_struct_B6diB18d2i2H10d3i2I6d().unpack(str[start:end])
      self.is_valid = bool(self.is_valid)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_B6diB18d2i2H10d3i2I6d = None
def _get_struct_B6diB18d2i2H10d3i2I6d():
    global _struct_B6diB18d2i2H10d3i2I6d
    if _struct_B6diB18d2i2H10d3i2I6d is None:
        _struct_B6diB18d2i2H10d3i2I6d = struct.Struct("<B6diB18d2i2H10d3i2I6d")
    return _struct_B6diB18d2i2H10d3i2I6d
