# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from ros_interface/ParkingOutInfo.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import ros_interface.msg
import std_msgs.msg

class ParkingOutInfo(genpy.Message):
  _md5sum = "e521a1b6fe67f908288575c2442dfdff"
  _type = "ros_interface/ParkingOutInfo"
  _has_header = True  # flag to mark the presence of a Header object
  _full_text = """Header   header     # timestamp is included in header
int32   parking_out_id     # 若车位有id，同停车位id
int32   parking_direction_type     #  
bool   is_parking_out_enable     # true可泊出，false不可泊出
Point3D   parking_out_point     # 世界坐标系下提车点位置
float64   theta     # 世界坐标系下的夹角（单位rad），提车点与正东方向夹角

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
string frame_id

================================================================================
MSG: ros_interface/Point3D
float64   x     # 位置坐标x
float64   y     # 位置坐标y
float64   z     # 位置坐标z
"""
  __slots__ = ['header','parking_out_id','parking_direction_type','is_parking_out_enable','parking_out_point','theta']
  _slot_types = ['std_msgs/Header','int32','int32','bool','ros_interface/Point3D','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,parking_out_id,parking_direction_type,is_parking_out_enable,parking_out_point,theta

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(ParkingOutInfo, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.parking_out_id is None:
        self.parking_out_id = 0
      if self.parking_direction_type is None:
        self.parking_direction_type = 0
      if self.is_parking_out_enable is None:
        self.is_parking_out_enable = False
      if self.parking_out_point is None:
        self.parking_out_point = ros_interface.msg.Point3D()
      if self.theta is None:
        self.theta = 0.
    else:
      self.header = std_msgs.msg.Header()
      self.parking_out_id = 0
      self.parking_direction_type = 0
      self.is_parking_out_enable = False
      self.parking_out_point = ros_interface.msg.Point3D()
      self.theta = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_2iB4d().pack(_x.parking_out_id, _x.parking_direction_type, _x.is_parking_out_enable, _x.parking_out_point.x, _x.parking_out_point.y, _x.parking_out_point.z, _x.theta))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.parking_out_point is None:
        self.parking_out_point = ros_interface.msg.Point3D()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 41
      (_x.parking_out_id, _x.parking_direction_type, _x.is_parking_out_enable, _x.parking_out_point.x, _x.parking_out_point.y, _x.parking_out_point.z, _x.theta,) = _get_struct_2iB4d().unpack(str[start:end])
      self.is_parking_out_enable = bool(self.is_parking_out_enable)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_2iB4d().pack(_x.parking_out_id, _x.parking_direction_type, _x.is_parking_out_enable, _x.parking_out_point.x, _x.parking_out_point.y, _x.parking_out_point.z, _x.theta))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.parking_out_point is None:
        self.parking_out_point = ros_interface.msg.Point3D()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 41
      (_x.parking_out_id, _x.parking_direction_type, _x.is_parking_out_enable, _x.parking_out_point.x, _x.parking_out_point.y, _x.parking_out_point.z, _x.theta,) = _get_struct_2iB4d().unpack(str[start:end])
      self.is_parking_out_enable = bool(self.is_parking_out_enable)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2iB4d = None
def _get_struct_2iB4d():
    global _struct_2iB4d
    if _struct_2iB4d is None:
        _struct_2iB4d = struct.Struct("<2iB4d")
    return _struct_2iB4d
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
