// Generated by gencpp from file ros_interface/CameraParkingInfoList.msg
// DO NOT EDIT!


#ifndef ROS_INTERFACE_MESSAGE_CAMERAPARKINGINFOLIST_H
#define ROS_INTERFACE_MESSAGE_CAMERAPARKINGINFOLIST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <ros_interface/CameraParkingInfo.h>
#include <ros_interface/CameraParkingStopper.h>

namespace ros_interface
{
template <class ContainerAllocator>
struct CameraParkingInfoList_
{
  typedef CameraParkingInfoList_<ContainerAllocator> Type;

  CameraParkingInfoList_()
    : header()
    , sensor_id(0)
    , camera_parking()
    , camera_parking_stoppers()
    , error_code(0)
    , is_valid(false)  {
    }
  CameraParkingInfoList_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , sensor_id(0)
    , camera_parking(_alloc)
    , camera_parking_stoppers(_alloc)
    , error_code(0)
    , is_valid(false)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int32_t _sensor_id_type;
  _sensor_id_type sensor_id;

   typedef std::vector< ::ros_interface::CameraParkingInfo_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::ros_interface::CameraParkingInfo_<ContainerAllocator> >> _camera_parking_type;
  _camera_parking_type camera_parking;

   typedef std::vector< ::ros_interface::CameraParkingStopper_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::ros_interface::CameraParkingStopper_<ContainerAllocator> >> _camera_parking_stoppers_type;
  _camera_parking_stoppers_type camera_parking_stoppers;

   typedef int32_t _error_code_type;
  _error_code_type error_code;

   typedef uint8_t _is_valid_type;
  _is_valid_type is_valid;





  typedef boost::shared_ptr< ::ros_interface::CameraParkingInfoList_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_interface::CameraParkingInfoList_<ContainerAllocator> const> ConstPtr;

}; // struct CameraParkingInfoList_

typedef ::ros_interface::CameraParkingInfoList_<std::allocator<void> > CameraParkingInfoList;

typedef boost::shared_ptr< ::ros_interface::CameraParkingInfoList > CameraParkingInfoListPtr;
typedef boost::shared_ptr< ::ros_interface::CameraParkingInfoList const> CameraParkingInfoListConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_interface::CameraParkingInfoList_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_interface::CameraParkingInfoList_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ros_interface::CameraParkingInfoList_<ContainerAllocator1> & lhs, const ::ros_interface::CameraParkingInfoList_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.sensor_id == rhs.sensor_id &&
    lhs.camera_parking == rhs.camera_parking &&
    lhs.camera_parking_stoppers == rhs.camera_parking_stoppers &&
    lhs.error_code == rhs.error_code &&
    lhs.is_valid == rhs.is_valid;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ros_interface::CameraParkingInfoList_<ContainerAllocator1> & lhs, const ::ros_interface::CameraParkingInfoList_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ros_interface

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ros_interface::CameraParkingInfoList_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_interface::CameraParkingInfoList_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_interface::CameraParkingInfoList_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_interface::CameraParkingInfoList_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_interface::CameraParkingInfoList_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_interface::CameraParkingInfoList_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_interface::CameraParkingInfoList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d4caa94d6814e1d645bcbe41c8c0b57d";
  }

  static const char* value(const ::ros_interface::CameraParkingInfoList_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd4caa94d6814e1d6ULL;
  static const uint64_t static_value2 = 0x45bcbe41c8c0b57dULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_interface::CameraParkingInfoList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_interface/CameraParkingInfoList";
  }

  static const char* value(const ::ros_interface::CameraParkingInfoList_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_interface::CameraParkingInfoList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header   header     # 消息头，时间戳使用接收的图像的时间戳\n"
"int32   sensor_id     # 安装的传感器id(camera,lidar,radar) ' 相机id: 0-front_center相机 1-front_left相机 2-front_right相机 3-left_front相机 4-left_back右后相机 5-right_front相机 6-right_back相机 7-back相机'  8-相机融合\n"
"CameraParkingInfo[] camera_parking # 检测出的障碍物数组\n"
"CameraParkingStopper[] camera_parking_stoppers # 检测出的限位器数组\n"
"int32   error_code     # 错误码（default = OK）\n"
"bool   is_valid     # 障碍物数据是否合法\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: ros_interface/CameraParkingInfo\n"
"Header   header     # timestamp is  included in header\n"
"int32   parking_space_id     # 停车位id\n"
"int32   parking_type     # PARKING_TYPE=0//无效泊车 PARKING_TYPE=1//垂直泊车 PARKING_TYPE=2//水平泊车 PARKING_TYPE=3//倾斜泊车\n"
"bool   is_parking_enable     # PARKING_ENABLE=0//不可泊入 PARKING_ENABLE=1//可泊入\n"
"float64   confidence     # 停车位置信度\n"
"Point3D   center_point_of_parking     # 车辆坐标系的停车位中心点\n"
"float64   theta     # 车辆坐标系下停车位的朝向\n"
"float64   width     # 停车位宽\n"
"float64   length     # 停车位长\n"
"float64   yaw_offset     # 停车位角度偏移量（倾斜车位），倾斜车位与道路边线夹角\n"
"ImageKeyPoint[] parking_points_in_image # 图像坐标系下停车位关键点，顺时针方向\n"
"\n"
"================================================================================\n"
"MSG: ros_interface/Point3D\n"
"float64   x     # 位置坐标x\n"
"float64   y     # 位置坐标y\n"
"float64   z     # 位置坐标z\n"
"\n"
"================================================================================\n"
"MSG: ros_interface/ImageKeyPoint\n"
"float64   x     # 车位图像关键点x坐标\n"
"float64   y     # 车位图像关键点y坐标\n"
"float64   confidence     # 置信度\n"
"\n"
"================================================================================\n"
"MSG: ros_interface/CameraParkingStopper\n"
"Header   header     # timestamp is  included in header\n"
"BBox2D   bbox2d     # 限位器图像框\n"
"\n"
"================================================================================\n"
"MSG: ros_interface/BBox2D\n"
"int16   xmin     # 图像框左上角的x坐标\n"
"int16   ymin     # 图像框左上角的y坐标\n"
"int16   xmax     # 图像框右下角的x坐标\n"
"int16   ymax     # 图像框右下角的y坐标\n"
;
  }

  static const char* value(const ::ros_interface::CameraParkingInfoList_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_interface::CameraParkingInfoList_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.sensor_id);
      stream.next(m.camera_parking);
      stream.next(m.camera_parking_stoppers);
      stream.next(m.error_code);
      stream.next(m.is_valid);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CameraParkingInfoList_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_interface::CameraParkingInfoList_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros_interface::CameraParkingInfoList_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "sensor_id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.sensor_id);
    s << indent << "camera_parking[]" << std::endl;
    for (size_t i = 0; i < v.camera_parking.size(); ++i)
    {
      s << indent << "  camera_parking[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::ros_interface::CameraParkingInfo_<ContainerAllocator> >::stream(s, indent + "    ", v.camera_parking[i]);
    }
    s << indent << "camera_parking_stoppers[]" << std::endl;
    for (size_t i = 0; i < v.camera_parking_stoppers.size(); ++i)
    {
      s << indent << "  camera_parking_stoppers[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::ros_interface::CameraParkingStopper_<ContainerAllocator> >::stream(s, indent + "    ", v.camera_parking_stoppers[i]);
    }
    s << indent << "error_code: ";
    Printer<int32_t>::stream(s, indent + "  ", v.error_code);
    s << indent << "is_valid: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.is_valid);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_INTERFACE_MESSAGE_CAMERAPARKINGINFOLIST_H
