// Generated by gencpp from file ros_interface/CommCommand.msg
// DO NOT EDIT!


#ifndef ROS_INTERFACE_MESSAGE_COMMCOMMAND_H
#define ROS_INTERFACE_MESSAGE_COMMCOMMAND_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <ros_interface/Command.h>

namespace ros_interface
{
template <class ContainerAllocator>
struct CommCommand_
{
  typedef CommCommand_<ContainerAllocator> Type;

  CommCommand_()
    : header()
    , name()
    , self_id(0)
    , commands()  {
    }
  CommCommand_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , name(_alloc)
    , self_id(0)
    , commands(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _name_type;
  _name_type name;

   typedef int8_t _self_id_type;
  _self_id_type self_id;

   typedef std::vector< ::ros_interface::Command_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::ros_interface::Command_<ContainerAllocator> >> _commands_type;
  _commands_type commands;





  typedef boost::shared_ptr< ::ros_interface::CommCommand_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_interface::CommCommand_<ContainerAllocator> const> ConstPtr;

}; // struct CommCommand_

typedef ::ros_interface::CommCommand_<std::allocator<void> > CommCommand;

typedef boost::shared_ptr< ::ros_interface::CommCommand > CommCommandPtr;
typedef boost::shared_ptr< ::ros_interface::CommCommand const> CommCommandConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_interface::CommCommand_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_interface::CommCommand_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ros_interface::CommCommand_<ContainerAllocator1> & lhs, const ::ros_interface::CommCommand_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.name == rhs.name &&
    lhs.self_id == rhs.self_id &&
    lhs.commands == rhs.commands;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ros_interface::CommCommand_<ContainerAllocator1> & lhs, const ::ros_interface::CommCommand_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ros_interface

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ros_interface::CommCommand_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_interface::CommCommand_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_interface::CommCommand_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_interface::CommCommand_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_interface::CommCommand_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_interface::CommCommand_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_interface::CommCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5dde9e6ab676652bc277f2b5bb9c1efa";
  }

  static const char* value(const ::ros_interface::CommCommand_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5dde9e6ab676652bULL;
  static const uint64_t static_value2 = 0xc277f2b5bb9c1efaULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_interface::CommCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_interface/CommCommand";
  }

  static const char* value(const ::ros_interface::CommCommand_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_interface::CommCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header   header     #  \n"
"string   name     # 发送指令的节点名称\n"
"int8   self_id     # 发送节点的ID号，参考apps描述\n"
"Command[] commands # 需要发送的指令，如果需要发送给多个节点，需要使用多个command\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: ros_interface/Command\n"
"string   target_module     # 目标节点名称\n"
"int8   target_id     # 目标节点ID\n"
"int32   target_switch     # 0:保持target_module的状态  1:打开target_module 2:关闭target_module\n"
;
  }

  static const char* value(const ::ros_interface::CommCommand_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_interface::CommCommand_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.name);
      stream.next(m.self_id);
      stream.next(m.commands);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CommCommand_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_interface::CommCommand_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros_interface::CommCommand_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.name);
    s << indent << "self_id: ";
    Printer<int8_t>::stream(s, indent + "  ", v.self_id);
    s << indent << "commands[]" << std::endl;
    for (size_t i = 0; i < v.commands.size(); ++i)
    {
      s << indent << "  commands[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::ros_interface::Command_<ContainerAllocator> >::stream(s, indent + "    ", v.commands[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_INTERFACE_MESSAGE_COMMCOMMAND_H
