// Generated by gencpp from file ros_interface/FrenetFramePoint.msg
// DO NOT EDIT!


#ifndef ROS_INTERFACE_MESSAGE_FRENETFRAMEPOINT_H
#define ROS_INTERFACE_MESSAGE_FRENETFRAMEPOINT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ros_interface
{
template <class ContainerAllocator>
struct FrenetFramePoint_
{
  typedef FrenetFramePoint_<ContainerAllocator> Type;

  FrenetFramePoint_()
    : s(0.0)
    , l(0.0)
    , dl(0.0)
    , ddl(0.0)  {
    }
  FrenetFramePoint_(const ContainerAllocator& _alloc)
    : s(0.0)
    , l(0.0)
    , dl(0.0)
    , ddl(0.0)  {
  (void)_alloc;
    }



   typedef double _s_type;
  _s_type s;

   typedef double _l_type;
  _l_type l;

   typedef double _dl_type;
  _dl_type dl;

   typedef double _ddl_type;
  _ddl_type ddl;





  typedef boost::shared_ptr< ::ros_interface::FrenetFramePoint_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_interface::FrenetFramePoint_<ContainerAllocator> const> ConstPtr;

}; // struct FrenetFramePoint_

typedef ::ros_interface::FrenetFramePoint_<std::allocator<void> > FrenetFramePoint;

typedef boost::shared_ptr< ::ros_interface::FrenetFramePoint > FrenetFramePointPtr;
typedef boost::shared_ptr< ::ros_interface::FrenetFramePoint const> FrenetFramePointConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_interface::FrenetFramePoint_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_interface::FrenetFramePoint_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ros_interface::FrenetFramePoint_<ContainerAllocator1> & lhs, const ::ros_interface::FrenetFramePoint_<ContainerAllocator2> & rhs)
{
  return lhs.s == rhs.s &&
    lhs.l == rhs.l &&
    lhs.dl == rhs.dl &&
    lhs.ddl == rhs.ddl;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ros_interface::FrenetFramePoint_<ContainerAllocator1> & lhs, const ::ros_interface::FrenetFramePoint_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ros_interface

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ros_interface::FrenetFramePoint_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_interface::FrenetFramePoint_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_interface::FrenetFramePoint_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_interface::FrenetFramePoint_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_interface::FrenetFramePoint_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_interface::FrenetFramePoint_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_interface::FrenetFramePoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5ecde306425599b635ce089fe72c9b83";
  }

  static const char* value(const ::ros_interface::FrenetFramePoint_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5ecde306425599b6ULL;
  static const uint64_t static_value2 = 0x35ce089fe72c9b83ULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_interface::FrenetFramePoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_interface/FrenetFramePoint";
  }

  static const char* value(const ::ros_interface::FrenetFramePoint_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_interface::FrenetFramePoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64   s     # 纵向位移\n"
"float64   l     # 横向位移\n"
"float64   dl     # 横向位移变化率\n"
"float64   ddl     # 横向位移变化率的变化率\n"
;
  }

  static const char* value(const ::ros_interface::FrenetFramePoint_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_interface::FrenetFramePoint_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.s);
      stream.next(m.l);
      stream.next(m.dl);
      stream.next(m.ddl);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct FrenetFramePoint_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_interface::FrenetFramePoint_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros_interface::FrenetFramePoint_<ContainerAllocator>& v)
  {
    s << indent << "s: ";
    Printer<double>::stream(s, indent + "  ", v.s);
    s << indent << "l: ";
    Printer<double>::stream(s, indent + "  ", v.l);
    s << indent << "dl: ";
    Printer<double>::stream(s, indent + "  ", v.dl);
    s << indent << "ddl: ";
    Printer<double>::stream(s, indent + "  ", v.ddl);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_INTERFACE_MESSAGE_FRENETFRAMEPOINT_H
