// Generated by gencpp from file ros_interface/ObstacleInteractiveTag.msg
// DO NOT EDIT!


#ifndef ROS_INTERFACE_MESSAGE_OBSTACLEINTERACTIVETAG_H
#define ROS_INTERFACE_MESSAGE_OBSTACLEINTERACTIVETAG_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ros_interface
{
template <class ContainerAllocator>
struct ObstacleInteractiveTag_
{
  typedef ObstacleInteractiveTag_<ContainerAllocator> Type;

  ObstacleInteractiveTag_()
    : interactive_tag(0)  {
    }
  ObstacleInteractiveTag_(const ContainerAllocator& _alloc)
    : interactive_tag(0)  {
  (void)_alloc;
    }



   typedef int32_t _interactive_tag_type;
  _interactive_tag_type interactive_tag;





  typedef boost::shared_ptr< ::ros_interface::ObstacleInteractiveTag_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_interface::ObstacleInteractiveTag_<ContainerAllocator> const> ConstPtr;

}; // struct ObstacleInteractiveTag_

typedef ::ros_interface::ObstacleInteractiveTag_<std::allocator<void> > ObstacleInteractiveTag;

typedef boost::shared_ptr< ::ros_interface::ObstacleInteractiveTag > ObstacleInteractiveTagPtr;
typedef boost::shared_ptr< ::ros_interface::ObstacleInteractiveTag const> ObstacleInteractiveTagConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_interface::ObstacleInteractiveTag_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_interface::ObstacleInteractiveTag_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ros_interface::ObstacleInteractiveTag_<ContainerAllocator1> & lhs, const ::ros_interface::ObstacleInteractiveTag_<ContainerAllocator2> & rhs)
{
  return lhs.interactive_tag == rhs.interactive_tag;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ros_interface::ObstacleInteractiveTag_<ContainerAllocator1> & lhs, const ::ros_interface::ObstacleInteractiveTag_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ros_interface

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ros_interface::ObstacleInteractiveTag_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_interface::ObstacleInteractiveTag_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_interface::ObstacleInteractiveTag_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_interface::ObstacleInteractiveTag_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_interface::ObstacleInteractiveTag_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_interface::ObstacleInteractiveTag_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_interface::ObstacleInteractiveTag_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c2e9ac94a7bb1e05f8d6dfc48cdf1b73";
  }

  static const char* value(const ::ros_interface::ObstacleInteractiveTag_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc2e9ac94a7bb1e05ULL;
  static const uint64_t static_value2 = 0xf8d6dfc48cdf1b73ULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_interface::ObstacleInteractiveTag_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_interface/ObstacleInteractiveTag";
  }

  static const char* value(const ::ros_interface::ObstacleInteractiveTag_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_interface::ObstacleInteractiveTag_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32   interactive_tag     #  \n"
;
  }

  static const char* value(const ::ros_interface::ObstacleInteractiveTag_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_interface::ObstacleInteractiveTag_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.interactive_tag);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ObstacleInteractiveTag_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_interface::ObstacleInteractiveTag_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros_interface::ObstacleInteractiveTag_<ContainerAllocator>& v)
  {
    s << indent << "interactive_tag: ";
    Printer<int32_t>::stream(s, indent + "  ", v.interactive_tag);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_INTERFACE_MESSAGE_OBSTACLEINTERACTIVETAG_H
