// Generated by gencpp from file ros_interface/ObstacleList.msg
// DO NOT EDIT!


#ifndef ROS_INTERFACE_MESSAGE_OBSTACLELIST_H
#define ROS_INTERFACE_MESSAGE_OBSTACLELIST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <ros_interface/Obstacle.h>

namespace ros_interface
{
template <class ContainerAllocator>
struct ObstacleList_
{
  typedef ObstacleList_<ContainerAllocator> Type;

  ObstacleList_()
    : header()
    , sensor_id(0)
    , obstacle()
    , error_code(0)
    , is_valid(false)
    , change_origin_flag(0)  {
    }
  ObstacleList_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , sensor_id(0)
    , obstacle(_alloc)
    , error_code(0)
    , is_valid(false)
    , change_origin_flag(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int32_t _sensor_id_type;
  _sensor_id_type sensor_id;

   typedef std::vector< ::ros_interface::Obstacle_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::ros_interface::Obstacle_<ContainerAllocator> >> _obstacle_type;
  _obstacle_type obstacle;

   typedef int32_t _error_code_type;
  _error_code_type error_code;

   typedef uint8_t _is_valid_type;
  _is_valid_type is_valid;

   typedef int32_t _change_origin_flag_type;
  _change_origin_flag_type change_origin_flag;





  typedef boost::shared_ptr< ::ros_interface::ObstacleList_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_interface::ObstacleList_<ContainerAllocator> const> ConstPtr;

}; // struct ObstacleList_

typedef ::ros_interface::ObstacleList_<std::allocator<void> > ObstacleList;

typedef boost::shared_ptr< ::ros_interface::ObstacleList > ObstacleListPtr;
typedef boost::shared_ptr< ::ros_interface::ObstacleList const> ObstacleListConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_interface::ObstacleList_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_interface::ObstacleList_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ros_interface::ObstacleList_<ContainerAllocator1> & lhs, const ::ros_interface::ObstacleList_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.sensor_id == rhs.sensor_id &&
    lhs.obstacle == rhs.obstacle &&
    lhs.error_code == rhs.error_code &&
    lhs.is_valid == rhs.is_valid &&
    lhs.change_origin_flag == rhs.change_origin_flag;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ros_interface::ObstacleList_<ContainerAllocator1> & lhs, const ::ros_interface::ObstacleList_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ros_interface

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ros_interface::ObstacleList_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_interface::ObstacleList_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_interface::ObstacleList_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_interface::ObstacleList_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_interface::ObstacleList_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_interface::ObstacleList_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_interface::ObstacleList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "557209d27fc972d8822c67ecf57858ce";
  }

  static const char* value(const ::ros_interface::ObstacleList_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x557209d27fc972d8ULL;
  static const uint64_t static_value2 = 0x822c67ecf57858ceULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_interface::ObstacleList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_interface/ObstacleList";
  }

  static const char* value(const ::ros_interface::ObstacleList_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_interface::ObstacleList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header   header     # 消息头\n"
"int32   sensor_id     # 安装的传感器id(camera,lidar,radar) ' 相机id: 0-front_center相机 1-front_left相机 2-front_right相机 3-left_front相机 4-left_back右后相机 5-right_front相机 6-right_back相机 7-back相机'  8-相机融合\n"
"Obstacle[] obstacle # 检测出的障碍物数组\n"
"int32   error_code     # 错误码（default = OK）\n"
"bool   is_valid     # 障碍物数据是否合法\n"
"int32   change_origin_flag     # 坐标切换状态（0-坐标系切换成功 1-坐标系切换中 2-坐标系切换故障）\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: ros_interface/Obstacle\n"
"Time   timestamp     # 时间戳\n"
"int32   id     # 障碍物id\n"
"float64   existence_prob     # 障碍物存在的概率\n"
"Time   create_time     # 障碍物被识别的时间戳\n"
"Time   last_updated_time     # 障碍物上一次更新的时间\n"
"Point3D   center_pos_vehicle     # 车辆坐标系下障碍物的中心位置\n"
"Point3D   center_pos_abs     # 世界坐标系下障碍物的中心位置\n"
"float64   theta_vehicle     # 车辆坐标系下障碍物的朝向\n"
"float64   theta_abs     # 世界坐标系下障碍物的朝向\n"
"Point3D   velocity_vehicle     # 车辆坐标系下障碍物的速度\n"
"Point3D   velocity_abs     # 世界坐标系下障碍物的速度\n"
"float64   length     # 障碍物长度\n"
"float64   width     # 障碍物宽度\n"
"float64   height     # 障碍物高度\n"
"ImageKeyPoint[] image_key_points # 图像坐标系下障碍物多边形\n"
"Point3D[] polygon_point_abs # 世界坐标系下障碍物多边形\n"
"Point3D[] polygon_point_vehicle # 车辆坐标系下障碍物多边形\n"
"float64   tracking_time     # 障碍物被追踪的时间\n"
"int32   type     # 障碍物类别： UNKNOWN = 0; UNKNOWN_MOVABLE = 1; UNKNOWN_UNMOVABLE = 2; PEDESTRIAN = 3; BICYCLE = 4; VEHICLE = 5;\n"
"float64   confidence     # 障碍物类别置信度\n"
"int32   confidence_type     # 障碍物置信度类别： CONFIDENCE_UNKNOWN = 0; CONFIDENCE_CNN = 1; CONFIDENCE_RADAR = 2;\n"
"Point3D[] drops # 障碍物轨迹点\n"
"Point3D   acceleration_vehicle     # 车辆坐标系下障碍物的加速度\n"
"Point3D   acceleration_abs     # 世界坐标系下障碍物的加速度\n"
"Point2D   anchor_point_image     # 障碍物尾框中心点(图像坐标系)\n"
"Point3D   anchor_point_vehicle     # 障碍物尾框中心点(车辆坐标系)\n"
"Point3D   anchor_point_abs     # 障碍物尾框中心点(世界坐标系)\n"
"BBox2D   bbox2d     # 障碍物图像框\n"
"BBox2D   bbox2d_rear     # 障碍物图像尾框\n"
"int32   sub_type     # 障碍物类别： ST_UNKNOWN = 0; ST_UNKNOWN_MOVABLE = 1; ST_UNKNOWN_UNMOVABLE = 2; ST_CAR = 3; ST_VAN = 4; ST_TRUCK = 5; ST_BUS = 6; ST_CYCLIST = 7; ST_MOTORCYCLIST = 8; ST_TRICYCLIST = 9; ST_PEDESTRIAN = 10; ST_TRAFFICCONE = 11; ST_PILLAR = 12; ST_SPEED_BUMP = 13;\n"
"float64   height_above_ground     # 障碍物近地点到地面的高度\n"
"float64[] position_abs_covariance # 世界坐标系下障碍物中心位置的协方差矩阵\n"
"float64[] velocity_abs_covariance # 世界坐标系下障碍物速度的协方差矩阵\n"
"float64[] acceleration_abs_covariance # 世界坐标系下障碍物加速度的协方差矩阵\n"
"float64   theta_abs_covariance     # 世界坐标系下障碍物朝向的协方差矩阵\n"
"float64[] position_vehicle_covariance # 车辆坐标系下障碍物中心位置的协方差矩阵\n"
"float64[] velocity_vehicle_covariance # 车辆坐标系下障碍物速度的协方差矩阵\n"
"float64[] acceleration_vehicle_covariance # 车辆坐标系下障碍物加速度的协方差矩阵\n"
"float64   theta_vehicle_covariance     # 车辆坐标系下障碍物朝向的协方差矩阵\n"
"SensorCalibrator   sensor_calibrator     # 传感器标定参数\n"
"uint8   cipv_flag     # 障碍物状态标志（0-CIPV 1-CIPS 2-LPIHP 3-RPIHP 4-NONE）\n"
"int32   lane_position     # 车道线位置 -2-NEXT_LEFT_LANE -1-LEFT_LANE 0-EGO_LANE 1-RIGHT_LANE 2-NEXT_RIGHT_LANE 3-OTHERS 4-UNKNOWN\n"
"float64   pihp_percentage     # 临车道车辆压线比例\n"
"int32   blinker_flag     # 障碍物车辆信号灯状态： 0-OFF 1-LEFT_TURN_VISIBLE 2-LEFT_TURN_ON 3-RIGHT_TURN_VISIBLE 4-RIGHT_TURN_ON 5-BRAKE_VISIBLE 6-BRAKE_ON 7-UNKNOWN\n"
"int32   fusion_type     # 融合障碍物类型 0-CAMERA 1-RADAR 2-LIDAR 3-ULTRASONIC 4-FUSED 5-UNKNOWN\n"
"\n"
"================================================================================\n"
"MSG: ros_interface/Time\n"
"uint32   sec     # 秒\n"
"uint32   nsec     # 纳秒\n"
"\n"
"================================================================================\n"
"MSG: ros_interface/Point3D\n"
"float64   x     # 位置坐标x\n"
"float64   y     # 位置坐标y\n"
"float64   z     # 位置坐标z\n"
"\n"
"================================================================================\n"
"MSG: ros_interface/ImageKeyPoint\n"
"float64   x     # 车位图像关键点x坐标\n"
"float64   y     # 车位图像关键点y坐标\n"
"float64   confidence     # 置信度\n"
"\n"
"================================================================================\n"
"MSG: ros_interface/Point2D\n"
"float64   x     # 位置坐标x\n"
"float64   y     # 位置坐标y\n"
"\n"
"================================================================================\n"
"MSG: ros_interface/BBox2D\n"
"int16   xmin     # 图像框左上角的x坐标\n"
"int16   ymin     # 图像框左上角的y坐标\n"
"int16   xmax     # 图像框右下角的x坐标\n"
"int16   ymax     # 图像框右下角的y坐标\n"
"\n"
"================================================================================\n"
"MSG: ros_interface/SensorCalibrator\n"
"Point3D   pose     # 传感器安装位置(相对于后轴中心点)\n"
"Point3D   angle     # 传感器安装角度(车体坐标系)\n"
;
  }

  static const char* value(const ::ros_interface::ObstacleList_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_interface::ObstacleList_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.sensor_id);
      stream.next(m.obstacle);
      stream.next(m.error_code);
      stream.next(m.is_valid);
      stream.next(m.change_origin_flag);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ObstacleList_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_interface::ObstacleList_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros_interface::ObstacleList_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "sensor_id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.sensor_id);
    s << indent << "obstacle[]" << std::endl;
    for (size_t i = 0; i < v.obstacle.size(); ++i)
    {
      s << indent << "  obstacle[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::ros_interface::Obstacle_<ContainerAllocator> >::stream(s, indent + "    ", v.obstacle[i]);
    }
    s << indent << "error_code: ";
    Printer<int32_t>::stream(s, indent + "  ", v.error_code);
    s << indent << "is_valid: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.is_valid);
    s << indent << "change_origin_flag: ";
    Printer<int32_t>::stream(s, indent + "  ", v.change_origin_flag);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_INTERFACE_MESSAGE_OBSTACLELIST_H
