// Generated by gencpp from file ros_interface/SLPoint.msg
// DO NOT EDIT!


#ifndef ROS_INTERFACE_MESSAGE_SLPOINT_H
#define ROS_INTERFACE_MESSAGE_SLPOINT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ros_interface
{
template <class ContainerAllocator>
struct SLPoint_
{
  typedef SLPoint_<ContainerAllocator> Type;

  SLPoint_()
    : s(0.0)
    , l(0.0)  {
    }
  SLPoint_(const ContainerAllocator& _alloc)
    : s(0.0)
    , l(0.0)  {
  (void)_alloc;
    }



   typedef double _s_type;
  _s_type s;

   typedef double _l_type;
  _l_type l;





  typedef boost::shared_ptr< ::ros_interface::SLPoint_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_interface::SLPoint_<ContainerAllocator> const> ConstPtr;

}; // struct SLPoint_

typedef ::ros_interface::SLPoint_<std::allocator<void> > SLPoint;

typedef boost::shared_ptr< ::ros_interface::SLPoint > SLPointPtr;
typedef boost::shared_ptr< ::ros_interface::SLPoint const> SLPointConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_interface::SLPoint_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_interface::SLPoint_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ros_interface::SLPoint_<ContainerAllocator1> & lhs, const ::ros_interface::SLPoint_<ContainerAllocator2> & rhs)
{
  return lhs.s == rhs.s &&
    lhs.l == rhs.l;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ros_interface::SLPoint_<ContainerAllocator1> & lhs, const ::ros_interface::SLPoint_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ros_interface

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ros_interface::SLPoint_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_interface::SLPoint_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_interface::SLPoint_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_interface::SLPoint_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_interface::SLPoint_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_interface::SLPoint_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_interface::SLPoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7c66d5c7666978e3c96dd85019fef0f4";
  }

  static const char* value(const ::ros_interface::SLPoint_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7c66d5c7666978e3ULL;
  static const uint64_t static_value2 = 0xc96dd85019fef0f4ULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_interface::SLPoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_interface/SLPoint";
  }

  static const char* value(const ::ros_interface::SLPoint_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_interface::SLPoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64   s     # 纵向位移\n"
"float64   l     # 横向位移\n"
;
  }

  static const char* value(const ::ros_interface::SLPoint_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_interface::SLPoint_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.s);
      stream.next(m.l);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SLPoint_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_interface::SLPoint_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros_interface::SLPoint_<ContainerAllocator>& v)
  {
    s << indent << "s: ";
    Printer<double>::stream(s, indent + "  ", v.s);
    s << indent << "l: ";
    Printer<double>::stream(s, indent + "  ", v.l);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_INTERFACE_MESSAGE_SLPOINT_H
