(cl:in-package ros_interface-msg)
(cl:export '(LANE_TYPE-VAL
          LANE_TYPE
          LANE_COLOR-VAL
          LANE_COLOR
          POS_TYPE-VAL
          POS_TYPE
          CURVE_VEHICLE-VAL
          CURVE_VEHICLE
          CURVE_IMAGE-VAL
          CURVE_IMAGE
          CURVE_ABS-VAL
          CURVE_ABS
          PTS_VEHICLE-VAL
          PTS_VEHICLE
          PTS_IMAGE-VAL
          PTS_IMAGE
          PTS_ABS-VAL
          PTS_ABS
          IMAGE_END_POINT-VAL
          IMAGE_END_POINT
          PTS_KEY-VAL
          PTS_KEY
          HD_LANE_ID-VAL
          HD_LANE_ID
          CONFIDENCE-VAL
          CONFIDENCE
          LANE_QUALITY-VAL
          LANE_QUALITY
          FUSED_LANE_TYPE-VAL
          FUSED_LANE_TYPE
          HOMOGRAPHY_MAT-VAL
          HOMOGRAPHY_MAT
          HOMOGRAPHY_MAT_INV-VAL
          HOMOGRAPHY_MAT_INV
          LANE_COORDINATE_TYPE-VAL
          LANE_COORDINATE_TYPE
          USE_TYPE-VAL
          USE_TYPE
          CREATE_TIME-VAL
          CREATE_TIME
))