(cl:in-package ros_interface-msg)
(cl:export '(IS_RSS_SAFE-VAL
          IS_RSS_SAFE
          CUR_DIST_LON-VAL
          CUR_DIST_LON
          RSS_SAFE_DIST_LON-VAL
          RSS_SAFE_DIST_LON
          ACC_LON_RANGE_MINIMUM-VAL
          ACC_LON_RANGE_MINIMUM
          ACC_LON_RANGE_MAXIMUM-VAL
          ACC_LON_RANGE_MAXIMUM
          ACC_LAT_LEFT_RANGE_MINIMUM-VAL
          ACC_LAT_LEFT_RANGE_MINIMUM
          ACC_LAT_LEFT_RANGE_MAXIMUM-VAL
          ACC_LAT_LEFT_RANGE_MAXIMUM
          ACC_LAT_RIGHT_RANGE_MINIMUM-VAL
          ACC_LAT_RIGHT_RANGE_MINIMUM
          ACC_LAT_RIGHT_RANGE_MAXIMUM-VAL
          ACC_LAT_RIGHT_RANGE_MAXIMUM
))