(cl:in-package ros_interface-msg)
(cl:export '(HEADER-VAL
          HEADER
          MOVING_STATUS-VAL
          MOVING_STATUS
          STEER_DRIVING_MODE-VAL
          STEER_DRIVING_MODE
          STEERING_VALUE-VAL
          STEERING_VALUE
          STEERING_TORQUE_NM-VAL
          STEERING_TORQUE_NM
          STEERING_RATE_DPS-VAL
          STEERING_RATE_DPS
          SPEED_MPS-VAL
          SPEED_MPS
          VEH_SPD_VLD-VAL
          VEH_SPD_VLD
          GEAR-VAL
          GEAR
          GEAR_VLD-VAL
          GEAR_VLD
          WHEEL_DIRECTION_RR-VAL
          WHEEL_DIRECTION_RR
          WHEEL_SPD_RR-VAL
          WHEEL_SPD_RR
          WHEEL_DIRECTION_RL-VAL
          WHEEL_DIRECTION_RL
          WHEEL_SPD_RL-VAL
          WHEEL_SPD_RL
          WHEEL_DIRECTION_FR-VAL
          WHEEL_DIRECTION_FR
          WHEEL_SPD_FR-VAL
          WHEEL_SPD_FR
          WHEEL_DIRECTION_FL-VAL
          WHEEL_DIRECTION_FL
          WHEEL_SPD_FL-VAL
          WHEEL_SPD_FL
          YAW_RATE-VAL
          YAW_RATE
          WSS_FL_EDGES_SUM-VAL
          WSS_FL_EDGES_SUM
          WSS_FR_EDGES_SUM-VAL
          WSS_FR_EDGES_SUM
          WSS_RL_EDGES_SUM-VAL
          WSS_RL_EDGES_SUM
          WSS_RR_EDGES_SUM-VAL
          WSS_RR_EDGES_SUM
          WSS_FL_EDGES_SUM_VLD-VAL
          WSS_FL_EDGES_SUM_VLD
          WSS_FR_EDGES_SUM_VLD-VAL
          WSS_FR_EDGES_SUM_VLD
          WSS_RL_EDGES_SUM_VLD-VAL
          WSS_RL_EDGES_SUM_VLD
          WSS_RR_EDGES_SUM_VLD-VAL
          WSS_RR_EDGES_SUM_VLD
          VEH_LAT_ACCEL-VAL
          VEH_LAT_ACCEL
          VEH_LGT_ACCEL-VAL
          VEH_LGT_ACCEL
          VEH_LAT_ACCEL_VLD-VAL
          VEH_LAT_ACCEL_VLD
          VEH_LGT_ACCEL_VLD-VAL
          VEH_LGT_ACCEL_VLD
))