(cl:in-package ros_interface-msg)
(cl:export '(SENSOR_ID-VAL
          SENSOR_ID
          NVM_READ_STATUS-VAL
          NVM_READ_STATUS
          NVM_WRITE_STATUS-VAL
          NVM_WRITE_STATUS
          RADAR_STATE_ERROR-VAL
          RADAR_STATE_ERROR
          RADAR_STATE_MODE-VAL
          RADAR_STATE_MODE
          MAX_DISTANCE-VAL
          MAX_DISTANCE
          SORT_INDEX-VAL
          SORT_INDEX
          RADAR_POWER-VAL
          RADAR_POWER
          CTL_RELAY-VAL
          CTL_RELAY
          OUTPUT_TYPE-VAL
          OUTPUT_TYPE
          SEND_QUALITY-VAL
          SEND_QUALITY
          SEND_EXTINFO-VAL
          SEND_EXTINFO
          MOTION_RX_STATE-VAL
          MOTION_RX_STATE
          RCS_THRESHOLD-VAL
          RCS_THRESHOLD
          CONNECTOR_DIRECTION-VAL
          CONNECTOR_DIRECTION
          RADAR_POSITION-VAL
          RADAR_POSITION
          HW_ERROR-VAL
          HW_ERROR
))