(cl:in-package ros_interface-msg)
(cl:export '(PERSISTENT_ERROR-VAL
          PERSISTENT_ERROR
          TEMPORARY_ERROR-VAL
          TEMPORARY_ERROR
          INTERFERENCE_ERROR-VAL
          INTERFERENCE_ERROR
          TEMPERATURE_ERROR-VAL
          TEMPERATURE_ERROR
          VOLTAGE_ERROR-VAL
          VOLTAGE_ERROR
          BLOCK_ERROR-VAL
          BLOCK_ERROR
          BROADCAST_ERROR-VAL
          BROADCAST_ERROR
          ELECTRIC_AXIS_ERROR-VAL
          ELECTRIC_AXIS_ERROR
          CONFIG_ERROR-VAL
          CONFIG_ERROR
          CALIBRATION_ERROR-VAL
          CALIBRATION_ERROR
))