(cl:in-package ros_interface-msg)
(cl:export '(HEADER-VAL
          HEADER
          X-VAL
          X
          Y-VAL
          Y
          Z-VAL
          Z
          TIMESTAMP-VAL
          TIMESTAMP
          ROLL-VAL
          ROLL
          PITCH-VAL
          PITCH
          YAW-VAL
          YAW
          HEADING-VAL
          HEADING
          KAPPA-VAL
          KAPPA
          LINEAR_VELOCITY-VAL
          LINEAR_VELOCITY
          ANGULAR_VELOCITY-VAL
          ANGULAR_VELOCITY
          LINEAR_ACCELERATION-VAL
          LINEAR_ACCELERATION
          GEAR-VAL
          GEAR
          DRIVING_MODE-VAL
          DRIVING_MODE
          POSE-VAL
          POSE
          FRONT_STEERING_VALUE-VAL
          FRONT_STEERING_VALUE
          REAR_STEERING_VALUE-VAL
          REAR_STEERING_VALUE
))