(cl:in-package ros_interface-msg)
(cl:export '(OBSTACLE_ID-VAL
          OBSTACLE_ID
          POLYGON_POINT-VAL
          POLYGON_POINT
          POSITION-VAL
          POSITION
          FRONT_POSITION-VAL
          FRONT_POSITION
          VELOCITY-VAL
          VELOCITY
          RAW_VELOCITY-VAL
          RAW_VELOCITY
          ACCELERATION-VAL
          ACCELERATION
          VELOCITY_HEADING-VAL
          VELOCITY_HEADING
          SPEED-VAL
          SPEED
          ACC-VAL
          ACC
          THETA-VAL
          THETA
          LENGTH-VAL
          LENGTH
          WIDTH-VAL
          WIDTH
          HEIGHT-VAL
          HEIGHT
          TRACKING_TIME-VAL
          TRACKING_TIME
          TIMESTAMP-VAL
          TIMESTAMP
          T_POSITION-VAL
          T_POSITION
          T_VELOCITY-VAL
          T_VELOCITY
          T_VELOCITY_HEADING-VAL
          T_VELOCITY_HEADING
          T_SPEED-VAL
          T_SPEED
          T_ACCELERATION-VAL
          T_ACCELERATION
          T_ACC-VAL
          T_ACC
          IS_STILL-VAL
          IS_STILL
          TYPE-VAL
          TYPE
          LABEL_UPDATE_TIME_DELTA-VAL
          LABEL_UPDATE_TIME_DELTA
          PRIORITY-VAL
          PRIORITY
          IS_NEAR_JUNCTION-VAL
          IS_NEAR_JUNCTION
          FUTURE_TRAJECTORY_POINTS-VAL
          FUTURE_TRAJECTORY_POINTS
          SHORT_TERM_PREDICTED_TRAJECTORY_POINTS-VAL
          SHORT_TERM_PREDICTED_TRAJECTORY_POINTS
          PREDICTED_TRAJECTORY-VAL
          PREDICTED_TRAJECTORY
          ADC_TRAJECTORY_POINT-VAL
          ADC_TRAJECTORY_POINT
))