(cl:in-package ros_interface-msg)
(cl:export '(HEADER-VAL
          HEADER
          IS_VALID-VAL
          IS_VALID
          LATITUDE-VAL
          LATITUDE
          LONGITUDE-VAL
          LONGITUDE
          ELEVATION-VAL
          ELEVATION
          UTM_POSITION-VAL
          UTM_POSITION
          UTM_ZONE_MUMBER-VAL
          UTM_ZONE_MUMBER
          UTM_ZONE_CHAR-VAL
          UTM_ZONE_CHAR
          ATTITUDE-VAL
          ATTITUDE
          LINEAR_VELOCITY-VAL
          LINEAR_VELOCITY
          SD_POSITION-VAL
          SD_POSITION
          SD_ATTITUDE-VAL
          SD_ATTITUDE
          SD_VELOCITY-VAL
          SD_VELOCITY
          CEP68-VAL
          CEP68
          CEP95-VAL
          CEP95
          SECOND-VAL
          SECOND
          SAT_USE_NUM-VAL
          SAT_USE_NUM
          SAT_IN_VIEW_NUM-VAL
          SAT_IN_VIEW_NUM
          SOLUTION_STATUS-VAL
          SOLUTION_STATUS
          POSITION_TYPE-VAL
          POSITION_TYPE
          P_DOP-VAL
          P_DOP
          H_DOP-VAL
          H_DOP
          V_DOP-VAL
          V_DOP
          ATTITUDE_DUAL-VAL
          ATTITUDE_DUAL
          SD_ANGLE_DUAL-VAL
          SD_ANGLE_DUAL
          BASE_LINE_LENGTH_DUAL-VAL
          BASE_LINE_LENGTH_DUAL
          SOLUTION_STATUS_DUAL-VAL
          SOLUTION_STATUS_DUAL
          POSITION_TYPE_DUAL-VAL
          POSITION_TYPE_DUAL
          SOLUTION_SOURCE_DUAL-VAL
          SOLUTION_SOURCE_DUAL
          AOC-VAL
          AOC
          RTK_BASELINE-VAL
          RTK_BASELINE
          ANGULAR_VELOCITY-VAL
          ANGULAR_VELOCITY
          ACCELERATION-VAL
          ACCELERATION
))