(cl:in-package ros_interface-msg)
(cl:export '(HEADER-VAL
          HEADER
          DRIVING_MODE-VAL
          DRIVING_MODE
          GEAR_LOCATION-VAL
          GEAR_LOCATION
          STEERING_VALUE-VAL
          STEERING_VALUE
          ACCEL_VALUE-VAL
          ACCEL_VALUE
          BRAKE_VALUE-VAL
          BRAKE_VALUE
          SPEED_MPS-VAL
          SPEED_MPS
          POSITION-VAL
          POSITION
          UTM_POSITION-VAL
          UTM_POSITION
          PITCH-VAL
          PITCH
          ROLL-VAL
          ROLL
          HEADING-VAL
          HEADING
          RTK_FLAG-VAL
          RTK_FLAG
          ORIGIN_LAT-VAL
          ORIGIN_LAT
          ORIGIN_LON-VAL
          ORIGIN_LON
          CURRENT_INS_YAW-VAL
          CURRENT_INS_YAW
          AUTO_SAFE-VAL
          AUTO_SAFE
          BATTERY_POWER_PERCENTAGE-VAL
          BATTERY_POWER_PERCENTAGE
          CHARGING_GUN_STATUS-VAL
          CHARGING_GUN_STATUS
          CHASSIS_ERROR_CODE-VAL
          CHASSIS_ERROR_CODE
          BRAKE_LAMP_STATUS-VAL
          BRAKE_LAMP_STATUS
          TURN_LAMP_STATUS-VAL
          TURN_LAMP_STATUS
          MERCATOR_POSITION-VAL
          MERCATOR_POSITION
))