(cl:in-package ros_interface-msg)
(cl:export '(ID-VAL
          ID
          POSITION-VAL
          POSITION
          THETA-VAL
          THETA
          VELOCITY-VAL
          VELOCITY
          LENGTH-VAL
          LENGTH
          WIDTH-VAL
          WIDTH
          HEIGHT-VAL
          HEIGHT
          POLYGON_POINT-VAL
          POLYGON_POINT
          TRACKING_TIME-VAL
          TRACKING_TIME
          TYPE-VAL
          TYPE
          LANE_POSITION-VAL
          LANE_POSITION
          CONFIDENCE-VAL
          CONFIDENCE
          TIMESTAMP-VAL
          TIMESTAMP
          CONFIDENCE_TYPE-VAL
          CONFIDENCE_TYPE
          DROPS-VAL
          DROPS
          ACCELERATION-VAL
          ACCELERATION
          ANCHOR_POINT-VAL
          ANCHOR_POINT
          BOUNDING_BOX-VAL
          BOUNDING_BOX
          SUB_TYPE-VAL
          SUB_TYPE
          HEIGHT_ABOVE_GROUND-VAL
          HEIGHT_ABOVE_GROUND
          POSITION_COVARIANCE-VAL
          POSITION_COVARIANCE
          VELOCITY_COVARIANCE-VAL
          VELOCITY_COVARIANCE
          ACCELERATION_COVARIANCE-VAL
          ACCELERATION_COVARIANCE
          LIGHT_STATUS-VAL
          LIGHT_STATUS
))