(cl:in-package ros_interface-msg)
(cl:export '(HEADER-VAL
          HEADER
          PARKING_SPACE_ID-VAL
          PARKING_SPACE_ID
          PARKING_TYPE-VAL
          PARKING_TYPE
          PARKING_STATUS-VAL
          PARKING_STATUS
          CONFIDENCE-VAL
          CONFIDENCE
          CENTER_POINT_OF_PARKING-VAL
          CENTER_POINT_OF_PARKING
          THETA-VAL
          THETA
          WIDTH-VAL
          WIDTH
          LENGTH-VAL
          LENGTH
          YAW_OFFSET-VAL
          YAW_OFFSET
          POLYGON-VAL
          POLYGON
          SENSOR_ID-VAL
          SENSOR_ID
          IS_LANE_WIDTH_VALID-VAL
          IS_LANE_WIDTH_VALID
          LANE_WIDTH-VAL
          LANE_WIDTH
          PARKING_STOPPERS-VAL
          PARKING_STOPPERS
          PARKING_DIRECTION_TYPE-VAL
          PARKING_DIRECTION_TYPE
          LEFT_OCCUPIED_STATUS-VAL
          LEFT_OCCUPIED_STATUS
          RIGHT_OCCUPIED_STATUS-VAL
          RIGHT_OCCUPIED_STATUS
          PARKING_SOURCE_TYPE-VAL
          PARKING_SOURCE_TYPE
))