(cl:in-package ros_interface-msg)
(cl:export '(HEADER-VAL
          HEADER
          TURN_LAMP_CTRL-VAL
          TURN_LAMP_CTRL
          HIGH_BEAM_CTRL-VAL
          HIGH_BEAM_CTRL
          LOW_BEAM_CTRL-VAL
          LOW_BEAM_CTRL
          HORN_CTRL-VAL
          HORN_CTRL
          FRONT_WIPER_CTRL-VAL
          FRONT_WIPER_CTRL
          REAR_WIPER_CTRL-VAL
          REAR_WIPER_CTRL
          POSITION_LAMP_CTRL-VAL
          POSITION_LAMP_CTRL
          FRONT_FOG_LAMP_CTRL-VAL
          FRONT_FOG_LAMP_CTRL
          REAR_FOG_LAMP_CTRL-VAL
          REAR_FOG_LAMP_CTRL
          BRAKE_LAMP_CTRL-VAL
          BRAKE_LAMP_CTRL
          ALARM_LAMP_CTRL-VAL
          ALARM_LAMP_CTRL
          LF_DOOR_CTRL-VAL
          LF_DOOR_CTRL
          RF_DOOR_CTRL-VAL
          RF_DOOR_CTRL
          LR_DOOR_CTRL-VAL
          LR_DOOR_CTRL
          RR_DOOR_CTRL-VAL
          RR_DOOR_CTRL
))