(cl:in-package ros_interface-msg)
(cl:export '(HEADER-VAL
          HEADER
          TOTAL_PATH_LENGTH-VAL
          TOTAL_PATH_LENGTH
          TOTAL_PATH_TIME-VAL
          TOTAL_PATH_TIME
          TRAJECTORY_POINTS-VAL
          TRAJECTORY_POINTS
          CAR_ACTION-VAL
          CAR_ACTION
          BEHAVIOUR_LAT_STATE-VAL
          BEHAVIOUR_LAT_STATE
          BEHAVIOUR_LON_STATE-VAL
          BEHAVIOUR_LON_STATE
          SCENARIO-VAL
          SCENARIO
          DRIVING_MODE-VAL
          DRIVING_MODE
          ADC_TRAJECTORY_TYPE-VAL
          ADC_TRAJECTORY_TYPE
          ESTOP-VAL
          ESTOP
          IS_REPLAN-VAL
          IS_REPLAN
          REPLAN_REASON-VAL
          REPLAN_REASON
          RIGHT_OF_WAY_STATUS-VAL
          RIGHT_OF_WAY_STATUS
          RSS_INFO-VAL
          RSS_INFO
))