(cl:in-package ros_interface-msg)
(cl:export '(POSITION_STD_DEV-VAL
          POSITION_STD_DEV
          ORIENTATION_STD_DEV-VAL
          ORIENTATION_STD_DEV
          LINEAR_VELOCITY_STD_DEV-VAL
          LINEAR_VELOCITY_STD_DEV
          LINEAR_ACCELERATION_STD_DEV-VAL
          LINEAR_ACCELERATION_STD_DEV
          ANGULAR_VELOCITY_STD_DEV-VAL
          ANGULAR_VELOCITY_STD_DEV
))