// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MSG_V_1_0_0.proto

#include "MSG_V_1_0_0.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
extern PROTOBUF_INTERNAL_EXPORT_MSG_5fV_5f1_5f0_5f0_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<2> scc_info_MsgHead_MSG_5fV_5f1_5f0_5f0_2eproto;
extern PROTOBUF_INTERNAL_EXPORT_google_2fprotobuf_2fwrappers_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_StringValue_google_2fprotobuf_2fwrappers_2eproto;
extern PROTOBUF_INTERNAL_EXPORT_google_2fprotobuf_2fwrappers_2eproto ::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_UInt64Value_google_2fprotobuf_2fwrappers_2eproto;
class MsgHeadDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<MsgHead> _instance;
} _MsgHead_default_instance_;
class JoyMessageDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<JoyMessage> _instance;
} _JoyMessage_default_instance_;
static void InitDefaultsscc_info_JoyMessage_MSG_5fV_5f1_5f0_5f0_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::_JoyMessage_default_instance_;
    new (ptr) ::JoyMessage();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<1> scc_info_JoyMessage_MSG_5fV_5f1_5f0_5f0_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 1, 0, InitDefaultsscc_info_JoyMessage_MSG_5fV_5f1_5f0_5f0_2eproto}, {
      &scc_info_MsgHead_MSG_5fV_5f1_5f0_5f0_2eproto.base,}};

static void InitDefaultsscc_info_MsgHead_MSG_5fV_5f1_5f0_5f0_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::_MsgHead_default_instance_;
    new (ptr) ::MsgHead();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<2> scc_info_MsgHead_MSG_5fV_5f1_5f0_5f0_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 2, 0, InitDefaultsscc_info_MsgHead_MSG_5fV_5f1_5f0_5f0_2eproto}, {
      &scc_info_StringValue_google_2fprotobuf_2fwrappers_2eproto.base,
      &scc_info_UInt64Value_google_2fprotobuf_2fwrappers_2eproto.base,}};

static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_MSG_5fV_5f1_5f0_5f0_2eproto[2];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_MSG_5fV_5f1_5f0_5f0_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_MSG_5fV_5f1_5f0_5f0_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_MSG_5fV_5f1_5f0_5f0_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::MsgHead, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::MsgHead, msgid_),
  PROTOBUF_FIELD_OFFSET(::MsgHead, msgtime_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::JoyMessage, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::JoyMessage, msghead_),
  PROTOBUF_FIELD_OFFSET(::JoyMessage, axes_),
  PROTOBUF_FIELD_OFFSET(::JoyMessage, buttons_),
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::MsgHead)},
  { 7, -1, sizeof(::JoyMessage)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::_MsgHead_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::_JoyMessage_default_instance_),
};

const char descriptor_table_protodef_MSG_5fV_5f1_5f0_5f0_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\021MSG_V_1_0_0.proto\032\036google/protobuf/wra"
  "ppers.proto\"e\n\007MsgHead\022+\n\005msgId\030\001 \001(\0132\034."
  "google.protobuf.StringValue\022-\n\007msgTime\030\002"
  " \001(\0132\034.google.protobuf.UInt64Value\"F\n\nJo"
  "yMessage\022\031\n\007msgHead\030\001 \001(\0132\010.MsgHead\022\014\n\004a"
  "xes\030\002 \003(\001\022\017\n\007buttons\030\003 \003(\rB+\n\'com.hyzx.d"
  "ispatchingsystem.common.protoP\001b\006proto3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_MSG_5fV_5f1_5f0_5f0_2eproto_deps[1] = {
  &::descriptor_table_google_2fprotobuf_2fwrappers_2eproto,
};
static ::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase*const descriptor_table_MSG_5fV_5f1_5f0_5f0_2eproto_sccs[2] = {
  &scc_info_JoyMessage_MSG_5fV_5f1_5f0_5f0_2eproto.base,
  &scc_info_MsgHead_MSG_5fV_5f1_5f0_5f0_2eproto.base,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_MSG_5fV_5f1_5f0_5f0_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_MSG_5fV_5f1_5f0_5f0_2eproto = {
  false, false, descriptor_table_protodef_MSG_5fV_5f1_5f0_5f0_2eproto, "MSG_V_1_0_0.proto", 279,
  &descriptor_table_MSG_5fV_5f1_5f0_5f0_2eproto_once, descriptor_table_MSG_5fV_5f1_5f0_5f0_2eproto_sccs, descriptor_table_MSG_5fV_5f1_5f0_5f0_2eproto_deps, 2, 1,
  schemas, file_default_instances, TableStruct_MSG_5fV_5f1_5f0_5f0_2eproto::offsets,
  file_level_metadata_MSG_5fV_5f1_5f0_5f0_2eproto, 2, file_level_enum_descriptors_MSG_5fV_5f1_5f0_5f0_2eproto, file_level_service_descriptors_MSG_5fV_5f1_5f0_5f0_2eproto,
};

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_MSG_5fV_5f1_5f0_5f0_2eproto = (static_cast<void>(::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_MSG_5fV_5f1_5f0_5f0_2eproto)), true);

// ===================================================================

class MsgHead::_Internal {
 public:
  static const PROTOBUF_NAMESPACE_ID::StringValue& msgid(const MsgHead* msg);
  static const PROTOBUF_NAMESPACE_ID::UInt64Value& msgtime(const MsgHead* msg);
};

const PROTOBUF_NAMESPACE_ID::StringValue&
MsgHead::_Internal::msgid(const MsgHead* msg) {
  return *msg->msgid_;
}
const PROTOBUF_NAMESPACE_ID::UInt64Value&
MsgHead::_Internal::msgtime(const MsgHead* msg) {
  return *msg->msgtime_;
}
void MsgHead::clear_msgid() {
  if (GetArena() == nullptr && msgid_ != nullptr) {
    delete msgid_;
  }
  msgid_ = nullptr;
}
void MsgHead::clear_msgtime() {
  if (GetArena() == nullptr && msgtime_ != nullptr) {
    delete msgtime_;
  }
  msgtime_ = nullptr;
}
MsgHead::MsgHead(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:MsgHead)
}
MsgHead::MsgHead(const MsgHead& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_msgid()) {
    msgid_ = new PROTOBUF_NAMESPACE_ID::StringValue(*from.msgid_);
  } else {
    msgid_ = nullptr;
  }
  if (from._internal_has_msgtime()) {
    msgtime_ = new PROTOBUF_NAMESPACE_ID::UInt64Value(*from.msgtime_);
  } else {
    msgtime_ = nullptr;
  }
  // @@protoc_insertion_point(copy_constructor:MsgHead)
}

void MsgHead::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_MsgHead_MSG_5fV_5f1_5f0_5f0_2eproto.base);
  ::memset(reinterpret_cast<char*>(this) + static_cast<size_t>(
      reinterpret_cast<char*>(&msgid_) - reinterpret_cast<char*>(this)),
      0, static_cast<size_t>(reinterpret_cast<char*>(&msgtime_) -
      reinterpret_cast<char*>(&msgid_)) + sizeof(msgtime_));
}

MsgHead::~MsgHead() {
  // @@protoc_insertion_point(destructor:MsgHead)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void MsgHead::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  if (this != internal_default_instance()) delete msgid_;
  if (this != internal_default_instance()) delete msgtime_;
}

void MsgHead::ArenaDtor(void* object) {
  MsgHead* _this = reinterpret_cast< MsgHead* >(object);
  (void)_this;
}
void MsgHead::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void MsgHead::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const MsgHead& MsgHead::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_MsgHead_MSG_5fV_5f1_5f0_5f0_2eproto.base);
  return *internal_default_instance();
}


void MsgHead::Clear() {
// @@protoc_insertion_point(message_clear_start:MsgHead)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (GetArena() == nullptr && msgid_ != nullptr) {
    delete msgid_;
  }
  msgid_ = nullptr;
  if (GetArena() == nullptr && msgtime_ != nullptr) {
    delete msgtime_;
  }
  msgtime_ = nullptr;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* MsgHead::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // .google.protobuf.StringValue msgId = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_msgid(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // .google.protobuf.UInt64Value msgTime = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 18)) {
          ptr = ctx->ParseMessage(_internal_mutable_msgtime(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* MsgHead::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:MsgHead)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .google.protobuf.StringValue msgId = 1;
  if (this->has_msgid()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        1, _Internal::msgid(this), target, stream);
  }

  // .google.protobuf.UInt64Value msgTime = 2;
  if (this->has_msgtime()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        2, _Internal::msgtime(this), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:MsgHead)
  return target;
}

size_t MsgHead::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:MsgHead)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .google.protobuf.StringValue msgId = 1;
  if (this->has_msgid()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *msgid_);
  }

  // .google.protobuf.UInt64Value msgTime = 2;
  if (this->has_msgtime()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *msgtime_);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void MsgHead::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:MsgHead)
  GOOGLE_DCHECK_NE(&from, this);
  const MsgHead* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<MsgHead>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:MsgHead)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:MsgHead)
    MergeFrom(*source);
  }
}

void MsgHead::MergeFrom(const MsgHead& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:MsgHead)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.has_msgid()) {
    _internal_mutable_msgid()->PROTOBUF_NAMESPACE_ID::StringValue::MergeFrom(from._internal_msgid());
  }
  if (from.has_msgtime()) {
    _internal_mutable_msgtime()->PROTOBUF_NAMESPACE_ID::UInt64Value::MergeFrom(from._internal_msgtime());
  }
}

void MsgHead::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:MsgHead)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void MsgHead::CopyFrom(const MsgHead& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:MsgHead)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool MsgHead::IsInitialized() const {
  return true;
}

void MsgHead::InternalSwap(MsgHead* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(MsgHead, msgtime_)
      + sizeof(MsgHead::msgtime_)
      - PROTOBUF_FIELD_OFFSET(MsgHead, msgid_)>(
          reinterpret_cast<char*>(&msgid_),
          reinterpret_cast<char*>(&other->msgid_));
}

::PROTOBUF_NAMESPACE_ID::Metadata MsgHead::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

class JoyMessage::_Internal {
 public:
  static const ::MsgHead& msghead(const JoyMessage* msg);
};

const ::MsgHead&
JoyMessage::_Internal::msghead(const JoyMessage* msg) {
  return *msg->msghead_;
}
JoyMessage::JoyMessage(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena),
  axes_(arena),
  buttons_(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:JoyMessage)
}
JoyMessage::JoyMessage(const JoyMessage& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      axes_(from.axes_),
      buttons_(from.buttons_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_msghead()) {
    msghead_ = new ::MsgHead(*from.msghead_);
  } else {
    msghead_ = nullptr;
  }
  // @@protoc_insertion_point(copy_constructor:JoyMessage)
}

void JoyMessage::SharedCtor() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&scc_info_JoyMessage_MSG_5fV_5f1_5f0_5f0_2eproto.base);
  msghead_ = nullptr;
}

JoyMessage::~JoyMessage() {
  // @@protoc_insertion_point(destructor:JoyMessage)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void JoyMessage::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  if (this != internal_default_instance()) delete msghead_;
}

void JoyMessage::ArenaDtor(void* object) {
  JoyMessage* _this = reinterpret_cast< JoyMessage* >(object);
  (void)_this;
}
void JoyMessage::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void JoyMessage::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const JoyMessage& JoyMessage::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_JoyMessage_MSG_5fV_5f1_5f0_5f0_2eproto.base);
  return *internal_default_instance();
}


void JoyMessage::Clear() {
// @@protoc_insertion_point(message_clear_start:JoyMessage)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  axes_.Clear();
  buttons_.Clear();
  if (GetArena() == nullptr && msghead_ != nullptr) {
    delete msghead_;
  }
  msghead_ = nullptr;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* JoyMessage::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // .MsgHead msgHead = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_msghead(), ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // repeated double axes = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 18)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedDoubleParser(_internal_mutable_axes(), ptr, ctx);
          CHK_(ptr);
        } else if (static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 17) {
          _internal_add_axes(::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr));
          ptr += sizeof(double);
        } else goto handle_unusual;
        continue;
      // repeated uint32 buttons = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 26)) {
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::PackedUInt32Parser(_internal_mutable_buttons(), ptr, ctx);
          CHK_(ptr);
        } else if (static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 24) {
          _internal_add_buttons(::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* JoyMessage::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:JoyMessage)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .MsgHead msgHead = 1;
  if (this->has_msghead()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(
        1, _Internal::msghead(this), target, stream);
  }

  // repeated double axes = 2;
  if (this->_internal_axes_size() > 0) {
    target = stream->WriteFixedPacked(2, _internal_axes(), target);
  }

  // repeated uint32 buttons = 3;
  {
    int byte_size = _buttons_cached_byte_size_.load(std::memory_order_relaxed);
    if (byte_size > 0) {
      target = stream->WriteUInt32Packed(
          3, _internal_buttons(), byte_size, target);
    }
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:JoyMessage)
  return target;
}

size_t JoyMessage::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:JoyMessage)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated double axes = 2;
  {
    unsigned int count = static_cast<unsigned int>(this->_internal_axes_size());
    size_t data_size = 8UL * count;
    if (data_size > 0) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
            static_cast<::PROTOBUF_NAMESPACE_ID::int32>(data_size));
    }
    int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(data_size);
    _axes_cached_byte_size_.store(cached_size,
                                    std::memory_order_relaxed);
    total_size += data_size;
  }

  // repeated uint32 buttons = 3;
  {
    size_t data_size = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      UInt32Size(this->buttons_);
    if (data_size > 0) {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
            static_cast<::PROTOBUF_NAMESPACE_ID::int32>(data_size));
    }
    int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(data_size);
    _buttons_cached_byte_size_.store(cached_size,
                                    std::memory_order_relaxed);
    total_size += data_size;
  }

  // .MsgHead msgHead = 1;
  if (this->has_msghead()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *msghead_);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void JoyMessage::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:JoyMessage)
  GOOGLE_DCHECK_NE(&from, this);
  const JoyMessage* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<JoyMessage>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:JoyMessage)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:JoyMessage)
    MergeFrom(*source);
  }
}

void JoyMessage::MergeFrom(const JoyMessage& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:JoyMessage)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  axes_.MergeFrom(from.axes_);
  buttons_.MergeFrom(from.buttons_);
  if (from.has_msghead()) {
    _internal_mutable_msghead()->::MsgHead::MergeFrom(from._internal_msghead());
  }
}

void JoyMessage::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:JoyMessage)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void JoyMessage::CopyFrom(const JoyMessage& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:JoyMessage)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool JoyMessage::IsInitialized() const {
  return true;
}

void JoyMessage::InternalSwap(JoyMessage* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  axes_.InternalSwap(&other->axes_);
  buttons_.InternalSwap(&other->buttons_);
  swap(msghead_, other->msghead_);
}

::PROTOBUF_NAMESPACE_ID::Metadata JoyMessage::GetMetadata() const {
  return GetMetadataStatic();
}


// @@protoc_insertion_point(namespace_scope)
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::MsgHead* Arena::CreateMaybeMessage< ::MsgHead >(Arena* arena) {
  return Arena::CreateMessageInternal< ::MsgHead >(arena);
}
template<> PROTOBUF_NOINLINE ::JoyMessage* Arena::CreateMaybeMessage< ::JoyMessage >(Arena* arena) {
  return Arena::CreateMessageInternal< ::JoyMessage >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
