// Generated by gencpp from file quad_msgs/MultiFootState.msg
// DO NOT EDIT!


#ifndef QUAD_MSGS_MESSAGE_MULTIFOOTSTATE_H
#define QUAD_MSGS_MESSAGE_MULTIFOOTSTATE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <quad_msgs/FootState.h>

namespace quad_msgs
{
template <class ContainerAllocator>
struct MultiFootState_
{
  typedef MultiFootState_<ContainerAllocator> Type;

  MultiFootState_()
    : header()
    , traj_index(0)
    , feet()  {
    }
  MultiFootState_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , traj_index(0)
    , feet(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint32_t _traj_index_type;
  _traj_index_type traj_index;

   typedef std::vector< ::quad_msgs::FootState_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::quad_msgs::FootState_<ContainerAllocator> >> _feet_type;
  _feet_type feet;





  typedef boost::shared_ptr< ::quad_msgs::MultiFootState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::quad_msgs::MultiFootState_<ContainerAllocator> const> ConstPtr;

}; // struct MultiFootState_

typedef ::quad_msgs::MultiFootState_<std::allocator<void> > MultiFootState;

typedef boost::shared_ptr< ::quad_msgs::MultiFootState > MultiFootStatePtr;
typedef boost::shared_ptr< ::quad_msgs::MultiFootState const> MultiFootStateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::quad_msgs::MultiFootState_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::quad_msgs::MultiFootState_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::quad_msgs::MultiFootState_<ContainerAllocator1> & lhs, const ::quad_msgs::MultiFootState_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.traj_index == rhs.traj_index &&
    lhs.feet == rhs.feet;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::quad_msgs::MultiFootState_<ContainerAllocator1> & lhs, const ::quad_msgs::MultiFootState_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace quad_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::quad_msgs::MultiFootState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::quad_msgs::MultiFootState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::quad_msgs::MultiFootState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::quad_msgs::MultiFootState_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::quad_msgs::MultiFootState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::quad_msgs::MultiFootState_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::quad_msgs::MultiFootState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0ebb914d22f2140664b36ac273cb4479";
  }

  static const char* value(const ::quad_msgs::MultiFootState_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0ebb914d22f21406ULL;
  static const uint64_t static_value2 = 0x64b36ac273cb4479ULL;
};

template<class ContainerAllocator>
struct DataType< ::quad_msgs::MultiFootState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "quad_msgs/MultiFootState";
  }

  static const char* value(const ::quad_msgs::MultiFootState_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::quad_msgs::MultiFootState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# This is a message to hold the state of all feet of a legged robot\n"
"#\n"
"# The states of each foot are stored in a vector of FootState messages\n"
"# (0 = front left, 1 = back left, 2 = front right, 3 = back right).\n"
"# Accurate timing information is stored in the header\n"
"\n"
"Header header\n"
"uint32 traj_index\n"
"quad_msgs/FootState[] feet\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: quad_msgs/FootState\n"
"# This is a message to hold the state of a single foot of a legged robot\n"
"#\n"
"# The states of each foot are stored in a vector of FootState messages\n"
"# Accurate timing information is stored in the header\n"
"\n"
"Header header\n"
"uint32 traj_index\n"
"geometry_msgs/Vector3 position\n"
"geometry_msgs/Vector3 velocity\n"
"geometry_msgs/Vector3 acceleration\n"
"bool contact\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::quad_msgs::MultiFootState_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::quad_msgs::MultiFootState_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.traj_index);
      stream.next(m.feet);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MultiFootState_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::quad_msgs::MultiFootState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::quad_msgs::MultiFootState_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "traj_index: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.traj_index);
    s << indent << "feet[]" << std::endl;
    for (size_t i = 0; i < v.feet.size(); ++i)
    {
      s << indent << "  feet[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::quad_msgs::FootState_<ContainerAllocator> >::stream(s, indent + "    ", v.feet[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // QUAD_MSGS_MESSAGE_MULTIFOOTSTATE_H
