
(cl:in-package :asdf)

(defsystem "quad_msgs-msg"
  :depends-on (:roslisp-msg-protocol :roslisp-utils :geometry_msgs-msg
               :nav_msgs-msg
               :sensor_msgs-msg
               :std_msgs-msg
)
  :components ((:file "_package")
    (:file "BodyForceEstimate" :depends-on ("_package_BodyForceEstimate"))
    (:file "_package_BodyForceEstimate" :depends-on ("_package"))
    (:file "BodyPlan" :depends-on ("_package_BodyPlan"))
    (:file "_package_BodyPlan" :depends-on ("_package"))
    (:file "BodyState" :depends-on ("_package_BodyState"))
    (:file "_package_BodyState" :depends-on ("_package"))
    (:file "ContactMode" :depends-on ("_package_ContactMode"))
    (:file "_package_ContactMode" :depends-on ("_package"))
    (:file "FootPlanDiscrete" :depends-on ("_package_FootPlanDiscrete"))
    (:file "_package_FootPlanDiscrete" :depends-on ("_package"))
    (:file "FootState" :depends-on ("_package_FootState"))
    (:file "_package_FootState" :depends-on ("_package"))
    (:file "GRFArray" :depends-on ("_package_GRFArray"))
    (:file "_package_GRFArray" :depends-on ("_package"))
    (:file "LegCommand" :depends-on ("_package_LegCommand"))
    (:file "_package_LegCommand" :depends-on ("_package"))
    (:file "LegCommandArray" :depends-on ("_package_LegCommandArray"))
    (:file "_package_LegCommandArray" :depends-on ("_package"))
    (:file "LegContactMode" :depends-on ("_package_LegContactMode"))
    (:file "_package_LegContactMode" :depends-on ("_package"))
    (:file "LocalPlan" :depends-on ("_package_LocalPlan"))
    (:file "_package_LocalPlan" :depends-on ("_package"))
    (:file "MotorCommand" :depends-on ("_package_MotorCommand"))
    (:file "_package_MotorCommand" :depends-on ("_package"))
    (:file "MultiFootPlanContinuous" :depends-on ("_package_MultiFootPlanContinuous"))
    (:file "_package_MultiFootPlanContinuous" :depends-on ("_package"))
    (:file "MultiFootPlanDiscrete" :depends-on ("_package_MultiFootPlanDiscrete"))
    (:file "_package_MultiFootPlanDiscrete" :depends-on ("_package"))
    (:file "MultiFootState" :depends-on ("_package_MultiFootState"))
    (:file "_package_MultiFootState" :depends-on ("_package"))
    (:file "RobotPlan" :depends-on ("_package_RobotPlan"))
    (:file "_package_RobotPlan" :depends-on ("_package"))
    (:file "RobotPlanDiagnostics" :depends-on ("_package_RobotPlanDiagnostics"))
    (:file "_package_RobotPlanDiagnostics" :depends-on ("_package"))
    (:file "RobotState" :depends-on ("_package_RobotState"))
    (:file "_package_RobotState" :depends-on ("_package"))
  ))